var searchValues = [["?, amy","877","?, Amy",""],
["?, angeline antionette","940","?, Angeline Antionette",""],
["?, baroness fitzscrob lady alice de essex","1790","?, Baroness FitzScrob Lady Alice De Essex",""],
["?, baroness fitzscrob lady alice de essex","1793","?, Baroness FitzScrob Lady Alice De Essex",""],
["?, cocubine","1798","?, Cocubine",""],
["?, cocubine","1802","?, Cocubine",""],
["?, elizabeth","579","?, Elizabeth",""],
["?, elizabeth","1605","?, Elizabeth",""],
["?, joan","623","?, Joan",""],
["?, sarah","314","?, Sarah",""],
["?, unknown","1051","?, Unknown",""],
["?, wife","989","?, Wife",""],
["(spears), ann","855","(Spears), Ann",""],
["[guerrero], laura m","874","[Guerrero], Laura M",""],
["3rd, richard i the fearless of normandy","1824","3rd, Richard I The Fearless of Normandy",""],
["abbott, benjamin","1469","Abbott, Benjamin",""],
["abbott, edward","1480","Abbott, Edward",""],
["abbott, elizabeth","1477","Abbott, Elizabeth",""],
["abbott, george","1461","Abbott, George",""],
["abbott, george v","1455","Abbott, George V",""],
["abbott, hannah","1478","Abbott, Hannah",""],
["abbott, john","819","Abbott, John",""],
["abbott, john","1460","Abbott, John",""],
["abbott, john","1472","Abbott, John",""],
["abbott, joseph","1474","Abbott, Joseph",""],
["abbott, joseph","1475","Abbott, Joseph",""],
["abbott, lydia","438","Abbott, Lydia",""],
["abbott, lydia","1470","Abbott, Lydia",""],
["abbott, mehitable","1465","Abbott, Mehitable",""],
["abbott, nathaniel","1479","Abbott, Nathaniel",""],
["abbott, nehemiah","1467","Abbott, Nehemiah",""],
["abbott, samuel","1468","Abbott, Samuel",""],
["abbott, sarah","1476","Abbott, Sarah",""],
["abbott, thomas","1463","Abbott, Thomas",""],
["abbott, timothy","1473","Abbott, Timothy",""],
["abbott, william","1471","Abbott, William",""],
["abbott barker, mary","1464","Abbott Barker, Mary",""],
["abbott ingalls, hannah","1466","Abbott Ingalls, Hannah",""],
["abbott iv, george (captain)","1462","Abbott IV, George (Captain)",""],
["alcock of the salem witch trials, frances elizabeth","1228","Alcock of the Salem witch trials, Frances Elizabeth",""],
["alexander, aaron","1153","Alexander, Aaron",""],
["alexander, aaron","1165","Alexander, AARON",""],
["alexander, aaron","1172","Alexander, Aaron",""],
["alexander, aaron","1175","Alexander, Aaron",""],
["alexander, abigail abby","1142","Alexander, Abigail Abby",""],
["alexander, alexander","1137","Alexander, Alexander",""],
["alexander, alice g","1170","Alexander, Alice G",""],
["alexander, amos","1157","Alexander, Amos",""],
["alexander, andrew","1182","Alexander, Andrew",""],
["alexander, andrew","1185","Alexander, Andrew",""],
["alexander, andrew","1527","Alexander, Andrew",""],
["alexander, andrew","1534","Alexander, Andrew",""],
["alexander, andrew","1539","Alexander, Andrew",""],
["alexander, archibald","1540","Alexander, Archibald",""],
["alexander, david","1154","Alexander, David",""],
["alexander, david aaron","1159","Alexander, David Aaron",""],
["alexander, deborah","1138","Alexander, Deborah",""],
["alexander, deborah","1148","Alexander, Deborah",""],
["alexander, eli","1156","Alexander, Eli",""],
["alexander, elizabeth","1139","Alexander, Elizabeth",""],
["alexander, elizabeth","1149","Alexander, Elizabeth",""],
["alexander, elizabeth","1528","Alexander, Elizabeth",""],
["alexander, emma c","1171","Alexander, Emma C",""],
["alexander, esther hetty","1145","Alexander, Esther Hetty",""],
["alexander, ezekiel","1160","Alexander, Ezekiel",""],
["alexander, ezekiel","1167","Alexander, Ezekiel",""],
["alexander, frances","1532","Alexander, Frances",""],
["alexander, francis","1188","Alexander, Francis",""],
["alexander, francis","1531","Alexander, Francis",""],
["alexander, francis","1537","Alexander, Francis",""],
["alexander, henry","1141","Alexander, Henry",""],
["alexander, james","1162","Alexander, James",""],
["alexander, james","1179","Alexander, James",""],
["alexander, james","1180","Alexander, James",""],
["alexander, james","1525","Alexander, James",""],
["alexander, james m","1144","Alexander, James M",""],
["alexander, jane","1140","Alexander, Jane",""],
["alexander, jane","1529","Alexander, Jane",""],
["alexander, jane","1536","Alexander, Jane",""],
["alexander, joseph","1524","Alexander, Joseph",""],
["alexander, josiah","941","ALEXANDER, Josiah",""],
["alexander, josiah","1150","Alexander, Josiah",""],
["alexander, leoie","1143","Alexander, Leoie",""],
["alexander, lewis h","1169","Alexander, Lewis H",""],
["alexander, martin","1135","Alexander, Martin",""],
["alexander, mary","914","Alexander, Mary",""],
["alexander, mary","1136","Alexander, Mary",""],
["alexander, mary","1184","Alexander, Mary",""],
["alexander, mary","1187","Alexander, Mary",""],
["alexander, moses","1161","Alexander, Moses",""],
["alexander, moses","1189","Alexander, Moses",""],
["alexander, nancy","1146","Alexander, Nancy",""],
["alexander, rebecca","1155","Alexander, Rebecca",""],
["alexander, rebecca","1158","Alexander, Rebecca",""],
["alexander, rebecca","1164","Alexander, Rebecca",""],
["alexander, rebecca","1174","Alexander, Rebecca",""],
["alexander, robert","1521","Alexander, Robert",""],
["alexander, robert","1538","Alexander, Robert",""],
["alexander, samuel","1152","Alexander, SAMUEL",""],
["alexander, samuel","1181","Alexander, Samuel",""],
["alexander, samuel, jr.","1186","Alexander, Samuel, Jr.",""],
["alexander, sarah","1163","Alexander, Sarah",""],
["alexander, sarah","1166","Alexander, Sarah",""],
["alexander, sarah","1183","Alexander, Sarah",""],
["alexander, squire","1147","Alexander, Squire",""],
["alexander, thomas","1530","Alexander, Thomas",""],
["alexander, william","1173","Alexander, William",""],
["alexander, william","1526","Alexander, William",""],
["alexander, william","1533","Alexander, William",""],
["alexander, william","1535","Alexander, William",""],
["alexander, william e","1168","Alexander, William E",""],
["allerton, sarah","846","Allerton, Sarah",""],
["alycel, cycely","645","Alycel, Cycely",""],
["andersen, ann","1222","Andersen, Ann",""],
["antwerp, fela van","1350","Antwerp, Fela Van",""],
["arnold, mary elizabeth","533","Arnold, Mary Elizabeth",""],
["ash, margery","1486","Ash, Margery",""],
["bacon, sarah","1209","Bacon, Sarah",""],
["baldolf, barbara","659","Baldolf, Barbara",""],
["banks, lucinda","1753","Banks, Lucinda",""],
["bardolf, cecily","660","Bardolf, Cecily",""],
["bardolf, cicely","658","Bardolf, Cicely",""],
["bardolf, margaret eleanor","657","Bardolf, Margaret Eleanor",""],
["bardolph, alice","662","Bardolph, Alice",""],
["bardolph, barbara","661","Bardolph, Barbara",""],
["bardolph, thomas lord bardolph","656","Bardolph, Thomas Lord Bardolph",""],
["barfield, mary a.","1720","Barfield, Mary A.",""],
["bateson, carolyn beatrice","23","Bateson, Carolyn Beatrice",""],
["bateson, carrie b","209","BATESON, Carrie B",""],
["bateson, doris","372","Bateson, Doris",""],
["bateson, robert","31","BATESON, Robert",""],
["bateson, robert","370","BATESON, Robert",""],
["bateson, robert","371","Bateson, Robert",""],
["bateson jr., robet","373","Bateson Jr., Robet",""],
["bayeux, poppa de","1822","Bayeux, Poppa de",""],
["beebe, althea","247","Beebe, Althea",""],
["beebe, marietta","272","Beebe, Marietta",""],
["belcher, amanda","236","Belcher, Amanda",""],
["belcher, betsy","233","Belcher, Betsy",""],
["belcher, isaac","103","Belcher, Isaac",""],
["belcher, lewis","230","Belcher, Lewis",""],
["belcher, margaret","232","Belcher, Margaret",""],
["belcher, n. jane","226","Belcher, N. Jane",""],
["belcher, peter l.","227","Belcher, Peter L.",""],
["belcher, sarah","235","Belcher, Sarah",""],
["belcher, terrell t","231","Belcher, Terrell T",""],
["belcher, wartis","234","Belcher, Wartis",""],
["belcher, william","229","Belcher, William",""],
["belcher brannon, mary polly (mahaffey)","69","Belcher Brannon, Mary Polly (Mahaffey)",""],
["bemis, john","883","Bemis, John",""],
["blackwell, alice","719","Blackwell, Alice",""],
["blackwell, john andrew","74","Blackwell, John Andrew",""],
["blackwell, john edward","73","Blackwell, John Edward",""],
["blake, mary","276","Blake, Mary",""],
["bland, jane","1239","Bland, Jane",""],
["boardman, mary","341","Boardman, Mary",""],
["boyce, remember","1301","Boyce, Remember",""],
["boyden, clarissa  clary  marion","1638","Boyden, Clarissa  Clary  Marion",""],
["boyles, derrick","872","Boyles, Derrick",""],
["bradley, susanna","1609","Bradley, Susanna",""],
["brannon, aggatha","104","Brannon, Aggatha",""],
["brannon, james m","105","Brannon, James M",""],
["brannon, margaret anne","90","Brannon, Margaret Anne",""],
["brannon, mary elizabeth","94","Brannon, Mary Elizabeth",""],
["brannon, sarah jane sallie","91","Brannon, Sarah Jane Sallie",""],
["bretagne, sporte de","1803","Bretagne, Sporte De",""],
["brooks, hannah","292","Brooks, Hannah",""],
["burk, berry","106","Burk, Berry",""],
["burk, doulan","128","Burk, doulan",""],
["burk, elizabeth","124","Burk, Elizabeth",""],
["burk, henry","131","Burk, henry",""],
["burk, j a","129","Burk, J A",""],
["burk, ja","130","Burk, JA",""],
["burk, lumpkin","80","Burk, Lumpkin",""],
["burk, sarah l","126","Burk, sarah l",""],
["burke, alfred","84","Burke, Alfred",""],
["burke, ann  annie  lee","68","Burke, Ann  Annie  Lee",""],
["burke, bernice","65","Burke, Bernice",""],
["burke, boyce lee","63","Burke, Boyce Lee",""],
["burke, cletus j","67","Burke, Cletus J",""],
["burke, eva","62","Burke, Eva",""],
["burke, grady","75","Burke, Grady",""],
["burke, henry curtis","11","Burke, Henry Curtis",""],
["burke, james matthew buddy","81","BURKE, JAMES MATTHEW Buddy",""],
["burke, jean","223","Burke, Jean",""],
["burke, john g","82","Burke, John G",""],
["burke, joseph taylor","50","Burke, Joseph Taylor",""],
["burke, kenneth i","111","Burke, Kenneth I",""],
["burke, kenneth i","224","Burke, Kenneth I",""],
["burke, larkin king","76","Burke, Larkin King",""],
["burke, lita d","110","Burke, Lita D",""],
["burke, lita d","225","Burke, Lita D",""],
["burke, lorena","66","Burke, Lorena",""],
["burke, loyd ernest","64","Burke, Loyd Ernest",""],
["burke, maberry","85","Burke, Maberry",""],
["burke, marilyn m","16","Burke, Marilyn M",""],
["burke, mary elizabeth","125","Burke, Mary Elizabeth",""],
["burke, mathew","127","Burke, Mathew",""],
["burke, myrtle","61","Burke, Myrtle",""],
["burke, sarah","83","BURKE, Sarah",""],
["burke, susanna e  annie ","79","Burke, Susanna E  Annie ",""],
["burke, velda j","109","Burke, Velda J",""],
["burks, billy","72","Burks, Billy",""],
["burks, radah","71","Burks, Radah",""],
["cady, susanna","296","Cady, Susanna",""],
["cameron, archibald","346","Cameron, Archibald",""],
["cameron, charles","343","Cameron, Charles",""],
["cameron, ellen e.","344","Cameron, Ellen E.",""],
["cameron, mahala a.","348","Cameron, Mahala A.",""],
["cameron, rachel i.","347","Cameron, Rachel I.",""],
["cameron, sarah e.","345","Cameron, Sarah E.",""],
["castell, agnes","1495","Castell, Agnes",""],
["castell, edward","1497","Castell, Edward",""],
["castell, martha","822","CASTELL, Martha",""],
["castell, martha","1490","Castell, Martha",""],
["castell, robert","1492","Castell, Robert",""],
["castell, robert","1496","Castell, Robert",""],
["cathey, elizabeth","908","Cathey, Elizabeth",""],
["chandler, hannah anne","1454","Chandler, Hannah Anne",""],
["chapin, olive victoria","1769","Chapin, Olive Victoria",""],
["chapman, mary","1625","Chapman, Mary",""],
["clare, lord of tonbridge, richard fitzgilbert, earl of","1796","Clare, Lord of Tonbridge, Richard FitzGilbert, Earl of",""],
["clark, abigail","1733","Clark, Abigail",""],
["clark, clarissa emeline","1381","Clark, Clarissa Emeline",""],
["clark, clarissa emmaline","1597","Clark, Clarissa Emmaline",""],
["clark, ora danielson","246","Clark, Ora Danielson",""],
["clark, sarah","1417","Clark, Sarah",""],
["clark, sophronia","1743","Clark, Sophronia",""],
["clarkson, lucy","134","Clarkson, Lucy",""],
["cokesey, walter de","667","COKESEY, Walter De",""],
["coleman, elizabeth  betty ","670","Coleman, Elizabeth  Betty ",""],
["cooke, elizabeth","1419","Cooke, Elizabeth",""],
["cooke, john","806","Cooke, John",""],
["cooke, john","1420","Cooke, John",""],
["cooke, sarah","494","COOKE, Sarah",""],
["corbet, elizabet","1781","Corbet, Elizabet",""],
["crow, elizabeth sarah","1097","Crow, Elizabeth Sarah",""],
["dame degrandison, blanche desavoie","654","Dame deGrandison, Blanche DeSavoie",""],
["danus, robert","1821","Danus, Robert",""],
["darden, benjamin","1028","Darden, Benjamin",""],
["darden, eleanor","1029","Darden, Eleanor",""],
["darden, henry","1030","Darden, Henry",""],
["darden, samuel","1031","Darden, Samuel",""],
["darden, stephen","1026","Darden, Stephen",""],
["darden durden, john","1024","Darden Durden, John",""],
["darwin, jane","1518","Darwin, Jane",""],
["darwin, john","1240","Darwin, John",""],
["darwin, john bland","1515","Darwin, John Bland",""],
["darwin, mary","1036","Darwin, Mary",""],
["darwin, matilda","1519","Darwin, Matilda",""],
["darwin, nancy","1514","Darwin, Nancy",""],
["darwin, pamela","1516","Darwin, Pamela",""],
["darwin, peyton bland","1517","Darwin, Peyton Bland",""],
["darwin, rachel","1513","Darwin, Rachel",""],
["darwin, rebecah motte","1510","Darwin, Rebecah Motte",""],
["darwin, robert g.","1511","Darwin, Robert G.",""],
["darwin, sarah ann","1512","Darwin, Sarah Ann",""],
["darwin, william f","1509","Darwin, William F",""],
["davis, adda atwood","32","Davis, Adda Atwood",""],
["davis, adda atwood","355","Davis, Adda Atwood",""],
["davis, andrew jackson","1559","Davis, Andrew Jackson",""],
["davis, anna e","351","Davis, Anna E",""],
["davis, anna e","359","Davis, Anna E",""],
["davis, anthony tinsley","1548","Davis, Anthony Tinsley",""],
["davis, beeba leachman","1552","Davis, Beeba Leachman",""],
["davis, constant","1560","Davis, Constant",""],
["davis, daniel r.","1558","Davis, Daniel R.",""],
["davis, elizabeth","1562","Davis, Elizabeth",""],
["davis, elizabeth","1573","Davis, Elizabeth",""],
["davis, elnathan","350","Davis, Elnathan",""],
["davis, elnathan","1554","Davis, Elnathan",""],
["davis, emily frances","1547","Davis, Emily Frances",""],
["davis, harden","1564","Davis, Harden",""],
["davis, henry polk","1550","Davis, Henry Polk",""],
["davis, israel","1563","Davis, Israel",""],
["davis, jackson","1549","Davis, Jackson",""],
["davis, james polk","1553","Davis, James Polk",""],
["davis, jesse","1551","Davis, Jesse",""],
["davis, joanna","1578","Davis, Joanna",""],
["davis, john","1571","Davis, John",""],
["davis, john","1575","Davis, John",""],
["davis, john dab","1574","Davis, John Dab",""],
["davis, john george","1556","Davis, John George",""],
["davis, john hazelton","357","Davis, John Hazelton",""],
["davis, joseph","1580","Davis, Joseph",""],
["davis, lewis newell","352","Davis, Lewis Newell",""],
["davis, lucy","354","Davis, Lucy",""],
["davis, mary jane","1545","Davis, Mary Jane",""],
["davis, matthew","1581","Davis, Matthew",""],
["davis, maude","358","Davis, Maude",""],
["davis, maude leona","353","Davis, Maude Leona",""],
["davis, micajah","1566","Davis, Micajah",""],
["davis, nancy ann","1567","Davis, Nancy Ann",""],
["davis, nathaniel","1546","Davis, Nathaniel",""],
["davis, rev. william","1542","Davis, Rev. William",""],
["davis, ruth","1579","Davis, Ruth",""],
["davis, samuel s","48","Davis, Samuel S",""],
["davis, sarah ann","1561","Davis, Sarah Ann",""],
["davis, susannah","1557","Davis, Susannah",""],
["davis, whitfield","1543","Davis, Whitfield",""],
["davis, william","1569","Davis, William",""],
["davis, william","1577","Davis, William",""],
["davis, william buchanan","1565","Davis, William Buchanan",""],
["davis, william v","1544","DAVIS, William V",""],
["davis, winfred","356","Davis, Winfred",""],
["de aunou, countess of d'eu and brione gunnora","1791","De Aunou, Countess of D'Eu and Brione Gunnora",""],
["de crepon, gunnora","1800","de Crepon, Gunnora",""],
["de franco hammond, valentina m","7","De Franco Hammond, Valentina M",""],
["degrandison, joan","1588","DeGrandison, Joan",""],
["degrandison, katherine","1584","DeGRANDISON, KATHERINE",""],
["de grandison, lady agnes","647","De Grandison, Lady Agnes",""],
["degrandison, othon","1587","DeGrandison, Othon",""],
["degrandison, peter","1582","DeGrandison, Peter",""],
["degrandison, thomas","1590","DeGrandison, Thomas",""],
["de grandison, william, sir, knight, lord of grandison, 1st baron of grandeson,","655","de Grandison, William, Sir, Knight, Lord of Grandison, 1st Baron of Grandeson,",""],
["degrandson, jacquette","1585","DeGrandson, Jacquette",""],
["de hieme, william","1817","De Hieme, William",""],
["de montanolier, judith","1816","De Montanolier, Judith",""],
["denorthwode, agnes","665","DeNorthwode, Agnes",""],
["denorthwood, john","663","DeNorthwood, John",""],
["denorthwood, roger","666","DeNorthwood, Roger",""],
["de pulford, jane","1771","de Pulford, Jane",""],
["de pulford, richard","1783","de Pulford, Richard",""],
["de pulford hammond/, sir richard","1780","de Pulford Hammond/, Sir Richard",""],
["de pulford hammond/, sir robert","1777","de Pulford Hammond/, Sir Robert",""],
["de pulford hammond/, sir robert","1782","De Pulford Hammond/, Sir Robert",""],
["de rouen, plantagenet, richard i, duke of normandy","1797","De Rouen, Plantagenet, Richard I, Duke of Normandy",""],
["desay, eustachia","1784","DeSay, Eustachia",""],
["d eu, william i","1813","d Eu, William I",""],
["dexter, alice","550","Dexter, Alice",""],
["dillisteir, elizabeth","360","DILLISTEIR, Elizabeth",""],
["dillisteir, laura a.","1052","DILLISTEIR, Laura A.",""],
["dillisteir, unk","369","DILLISTEIR, unk",""],
["dodd, ann","172","Dodd, Ann",""],
["dodd, catherine","152","Dodd, Catherine",""],
["dodd, elizabeth","107","DODD, ELIZABETH",""],
["dodd, elizabeth","155","DODD, Elizabeth",""],
["dodd, elizabeth","156","DODD, Elizabeth",""],
["dodd, elizabeth","168","Dodd, Elizabeth",""],
["dodd, elizabeth","177","Dodd, Elizabeth",""],
["dodd, frances","158","Dodd, Frances",""],
["dodd, green berry","145","Dodd, Green Berry",""],
["dodd, james","135","Dodd, James",""],
["dodd, james a","133","Dodd, James A",""],
["dodd, james a","144","Dodd, James A",""],
["dodd, james alexander","159","Dodd, James Alexander",""],
["dodd, jane","141","Dodd, Jane",""],
["dodd, joel jackson","142","Dodd, Joel Jackson",""],
["dodd, john","161","Dodd, John",""],
["dodd, john","163","Dodd, John",""],
["dodd, john","170","Dodd, John",""],
["dodd, john","185","Dodd, John",""],
["dodd, john h","139","Dodd, John H",""],
["dodd, john h","143","Dodd, John H",""],
["dodd, joseph","148","Dodd, Joseph",""],
["dodd, joseph c","154","Dodd, Joseph C",""],
["dodd, josiah","183","Dodd, Josiah",""],
["dodd, katherine","136","Dodd, Katherine",""],
["dodd, lucinda","157","Dodd, Lucinda",""],
["dodd, lydia","166","Dodd, Lydia",""],
["dodd, mary","165","Dodd, Mary",""],
["dodd, mary","176","Dodd, Mary",""],
["dodd, mary malissa","138","Dodd, Mary Malissa",""],
["dodd, mary midlock","162","Dodd, Mary Midlock",""],
["dodd, mm","137","Dodd, MM",""],
["dodd, nancy","160","Dodd, Nancy",""],
["dodd, nancy ann","179","Dodd, Nancy Ann",""],
["dodd, nancy lee","175","Dodd, Nancy Lee",""],
["dodd, patsy","151","Dodd, Patsy",""],
["dodd, phoebe","180","Dodd, Phoebe",""],
["dodd, rebecca","140","Dodd, Rebecca",""],
["dodd, samuel","164","Dodd, Samuel",""],
["dodd, samuel","167","Dodd, Samuel",""],
["dodd, sarah","147","Dodd, Sarah",""],
["dodd, sarah","169","Dodd, Sarah",""],
["dodd, sarah b","153","Dodd, Sarah B",""],
["dodd, sarah lee","182","Dodd, Sarah Lee",""],
["dodd, susannah","150","Dodd, Susannah",""],
["dodd, susannah marilda","146","Dodd, Susannah Marilda",""],
["dodd, thomas j","171","Dodd, Thomas J",""],
["dodd, william","173","Dodd, William",""],
["dodd, william","178","Dodd, William",""],
["dodd, william","181","Dodd, William",""],
["drake, sarah anne","1555","Drake, Sarah Anne",""],
["dunham, freelove","1341","Dunham, Freelove",""],
["dunham, mary","1377","Dunham, Mary",""],
["edminster, elizabeth (deliverance)","513","Edminster, Elizabeth (Deliverance)",""],
["eldridge, sylvia","441","Eldridge, Sylvia",""],
["esmond eastman/, sarah","509","Esmond Eastman/, Sarah",""],
["eu, geoffrey count of d","1815","Eu, Geoffrey Count of D",""],
["eu brionne, geoffrey count d","1814","EU BRIONNE, Geoffrey Count D",""],
["evreux, robert count of","1820","Evreux, Robert Count of",""],
["farr, elizabeth","1200","Farr, Elizabeth",""],
["faunce, abigail","1501","Faunce, Abigail",""],
["fela, purrity","1345","Fela, Purrity",""],
["fisk, mina b","193","Fisk, Mina B",""],
["fitch, anna","1284","Fitch, Anna",""],
["fitz geoffrey, count of brionne, gilbert crispin","1799","Fitz Geoffrey, Count of Brionne, Gilbert Crispin",""],
["fitzgodfrey, count of eu and brione sir gilbert  gislebert crispin ","1792","FitzGodfrey, Count of Eu and Brione Sir Gilbert  Gislebert Crispin ",""],
["fitzosberne, hugh lord dodleston blundus","1785","fitzOsberne, Hugh Lord Dodleston Blundus",""],
["fitzrichard, godfrey comte de brionne &amp; de eu","1795","FitzRichard, Godfrey Comte de Brionne &amp; de Eu",""],
["fitzrichard hammond/, osbern  sheriff of hereford ","1787","Fitzrichard Hammond/, Osbern  Sheriff of Hereford ",""],
["fitzscrob, baron fitzscrob of burford sir richard","1789","Fitzscrob, Baron FitzScrob of Burford Sir Richard",""],
["foster","1088","Foster",""],
["foster, anthony","1102","Foster, Anthony",""],
["foster, barbara","1108","Foster, Barbara",""],
["foster, barbara","1119","Foster, Barbara",""],
["foster, doshea","683","Foster, Doshea",""],
["foster, elizabeth","1065","Foster, Elizabeth",""],
["foster, elizabeth","1070","Foster, Elizabeth",""],
["foster, elizabeth","1072","Foster, Elizabeth",""],
["foster, elizabeth","1073","Foster, Elizabeth",""],
["foster, elizabeth","1083","Foster, Elizabeth",""],
["foster, elizabeth","1114","Foster, Elizabeth",""],
["foster, elizabeth","1250","Foster, Elizabeth",""],
["foster, ellen","1133","Foster, Ellen",""],
["foster, francis","1071","Foster, Francis",""],
["foster, francis","1074","Foster, Francis",""],
["foster, george","1079","Foster, George",""],
["foster sr, george","1081","Foster Sr, George",""],
["foster, george","1086","Foster, George",""],
["foster, george","1110","Foster, George",""],
["foster, hannah","1091","Foster, Hannah",""],
["foster, james","1084","Foster, James",""],
["foster, james","1177","Foster, James",""],
["foster, james","1247","Foster, James",""],
["foster, jane","1249","Foster, Jane",""],
["foster, jane jenny jincy miller","1069","Foster, Jane Jenny Jincy Miller",""],
["foster, jeffrey","1076","Foster, Jeffrey",""],
["foster, jennie lincoln","1649","Foster, Jennie Lincoln",""],
["foster, joel","1077","Foster, Joel",""],
["foster, john","1093","Foster, John",""],
["foster, john","1096","Foster, John",""],
["foster, john","1105","Foster, John",""],
["foster, john","1118","FOSTER, John",""],
["foster, john","1126","Foster, John",""],
["foster, john","1131","Foster, John",""],
["foster, john","1248","Foster, John",""],
["foster, joseph","1087","Foster, Joseph",""],
["foster, joseph","1109","Foster, Joseph",""],
["foster, joshua","1064","Foster, Joshua",""],
["foster, josiah","1085","Foster, Josiah",""],
["foster, josiah  black siah ","1066","Foster, Josiah  Black Siah ",""],
["foster, margaret","1115","Foster, Margaret",""],
["foster, mary","703","Foster, Mary",""],
["foster, mary","1078","Foster, Mary",""],
["foster, mary","1112","Foster, Mary",""],
["foster, mary singleton","1067","Foster, Mary Singleton",""],
["foster, richard","1111","Foster, Richard",""],
["foster, richard","1116","Foster, Richard",""],
["foster, richard","1127","Foster, Richard",""],
["foster, richard","1132","Foster, Richard",""],
["foster, richard james","1100","Foster, Richard James",""],
["foster, robert","1063","Foster, Robert",""],
["foster, robert","1090","Foster, Robert",""],
["foster, robert","1095","Foster, Robert",""],
["foster, robert","1103","Foster, Robert",""],
["foster, robert","1107","Foster, Robert",""],
["foster, robert","1128","Foster, Robert",""],
["foster, sarah johnson","1068","Foster, Sarah Johnson",""],
["foster jr, sir robert","1122","Foster Jr, Sir Robert",""],
["foster, susan","1129","Foster, Susan",""],
["foster, susannah","1134","Foster, Susannah",""],
["foster, thomas","1106","Foster, Thomas",""],
["foster, thomas","1120","Foster, Thomas",""],
["foster, thomas","1124","Foster, Thomas",""],
["foster, william","1075","Foster, William",""],
["foster, william","1082","Foster, William",""],
["foster, william","1089","Foster, William",""],
["foster, william","1104","Foster, William",""],
["foster, william","1113","Foster, William",""],
["foster, william","1117","Foster, William",""],
["foster, william","1125","Foster, William",""],
["foster, william","1130","Foster, William",""],
["foster, b.w., joshua","704","Foster, B.W., Joshua",""],
["france, richard ii of normandy of","1805","France, Richard II of Normandy of",""],
["frodsham, margery","1779","Frodsham, Margery",""],
["fuller, elizabeth","652","Fuller, Elizabeth",""],
["fuller, mary","1317","Fuller, Mary",""],
["gaona, blanca e","6","Gaona, Blanca E",""],
["gardner, lois","1265","Gardner, Lois",""],
["garner, mary","675","Garner, Mary",""],
["garner, mary","685","Garner, Mary",""],
["garnett, elizabeth","1094","Garnett, Elizabeth",""],
["garnett, elizabeth","1101","Garnett, Elizabeth",""],
["garnett, susannah","1099","Garnett, Susannah",""],
["garrold, agnes","582","Garrold, Agnes",""],
["garrold, agnes","595","Garrold, Agnes",""],
["garrold, mrs. roger","620","Garrold, Mrs. Roger",""],
["garrold, roger","621","Garrold, Roger",""],
["gibbs, barnabas","740","Gibbs, Barnabas",""],
["gibbs, bethiah","744","Gibbs, Bethiah",""],
["gibbs, cornelius","739","Gibbs, Cornelius",""],
["gibbs, ebenezer","736","Gibbs, Ebenezer",""],
["gibbs, jabez","734","gibbs, jabez",""],
["gibbs, jabez","735","Gibbs, Jabez",""],
["gibbs, job","745","Gibbs, Job",""],
["gibbs, sarah","742","Gibbs, Sarah",""],
["gibbs, thomas","732","Gibbs, Thomas",""],
["gibbs, thomas","741","Gibbs, Thomas",""],
["gibbs, thomas","743","Gibbs, Thomas",""],
["gibbs, warren","738","Gibbs, Warren",""],
["gibbs, william","737","Gibbs, William",""],
["gifford, anne","817","Gifford, Anne",""],
["gifford, bethiah","816","Gifford, Bethiah",""],
["gifford, christopher","896","Gifford, Christopher",""],
["gifford, dinah","814","Gifford, Dinah",""],
["gifford, fear","1726","Gifford, Fear",""],
["gifford, hannah","421","Gifford, Hannah",""],
["gifford, hannah","811","Gifford, Hannah",""],
["gifford, hannah","818","Gifford, Hannah",""],
["gifford, hannah","898","Gifford, Hannah",""],
["gifford, hannah","1309","Gifford, Hannah",""],
["gifford, hannaniah","901","Gifford, Hannaniah",""],
["gifford, james","904","Gifford, James",""],
["gifford, john","897","Gifford, John",""],
["gifford, john","902","Gifford, John",""],
["gifford, john","903","Gifford, John",""],
["gifford, jonathan","439","Gifford, Jonathan",""],
["gifford, maria","812","Gifford, Maria",""],
["gifford, mary","894","GIFFORD, Mary",""],
["gifford, mary","895","Gifford, Mary",""],
["gifford, patience","899","GIFFORD, Patience",""],
["gifford, peleg","813","Gifford, Peleg",""],
["gifford, philip","891","Gifford, Philip",""],
["gifford, rebecca","810","Gifford, Rebecca",""],
["gifford, silas","815","Gifford, Silas",""],
["gifford, stephen","900","Gifford, Stephen",""],
["gifford, william","809","Gifford, William",""],
["gifford, william","893","Gifford, William",""],
["goleman, kathy hammond","18","Goleman, Kathy Hammond",""],
["golemon, mark","60","Golemon, Mark",""],
["grace","649","Grace",""],
["graham, carson","853","Graham, Carson",""],
["graham, mary ann","531","Graham, Mary Ann",""],
["grandison, alice","1594","Grandison, Alice",""],
["grandison, alice de","1593","Grandison, Alice de",""],
["grandison, john de","1589","Grandison, John de",""],
["grandison, mabel de","1586","Grandison, Mabel de",""],
["grandison, otes de","1591","Grandison, Otes de",""],
["grandison, sibyl de","1583","Grandison, Sibyl de",""],
["grandson, x piers","1592","Grandson, X Piers",""],
["grant, elizabeth","892","Grant, Elizabeth",""],
["green, mary","1276","Green, Mary",""],
["gregory, sarah","905","Gregory, Sarah",""],
["gruffydd, nesta verch","1788","Gruffydd, Nesta Verch",""],
["guerrero, joshua daniel","56","Guerrero, Joshua Daniel",""],
["guerrero, patrick","55","Guerrero, Patrick",""],
["guerrero, patrick","875","Guerrero, Patrick",""],
["guerrero, stephanie","876","Guerrero, Stephanie",""],
["guisnes, heloise hawise de","1794","Guisnes, Heloise Hawise de",""],
["hall, martha","286","Hall, Martha",""],
["hamilton, cynthia","852","Hamilton, Cynthia",""],
["hamilton, daniel","1459","Hamilton, Daniel",""],
["hamilton, mary","1520","Hamilton, Mary",""],
["hamilton, thomas","1458","Hamilton, Thomas",""],
["hammon, elizabeth","404","Hammon, Elizabeth",""],
["hammon, walter","190","Hammon, Walter",""],
["hammond, abbie ann","1351","Hammond, Abbie Ann",""],
["hammond, abigail","449","Hammond, Abigail",""],
["hammond, abigail","542","Hammond, Abigail",""],
["hammond, abigail","1508","Hammond, Abigail",""],
["hammond, abigail","1666","Hammond, Abigail",""],
["hammond, abigail","1672","Hammond, Abigail",""],
["hammond, abigail","1742","Hammond, Abigail",""],
["hammond, abner","1330","Hammond, Abner",""],
["hammond, abner","1331","Hammond, Abner",""],
["hammond, adaline","405","Hammond, Adaline",""],
["hammond, alanson","426","Hammond, Alanson",""],
["hammond, allen","1741","Hammond, Allen",""],
["hammond, alonzo","1304","Hammond, Alonzo",""],
["hammond, alyssa marie","3","Hammond, Alyssa Marie",""],
["hammond, alyssa marie","1055","Hammond, Alyssa Marie",""],
["hammond, amanda","1318","Hammond, amanda",""],
["hammond, ammon","1366","Hammond, Ammon",""],
["hammond, amy","1279","Hammond, Amy",""],
["hammond, amy","1287","Hammond, Amy",""],
["hammond, andrea","434","Hammond, Andrea",""],
["hammond, andrew b","1286","Hammond, Andrew B",""],
["hammond, andria","1310","Hammond, Andria",""],
["hammond, ann","569","Hammond, Ann",""],
["hammond, ann","572","Hammond, Ann",""],
["hammond, anna","397","Hammond, Anna",""],
["hammond, anna","425","Hammond, Anna",""],
["hammond, anna","567","Hammond, Anna",""],
["hammond, ann maria","1380","Hammond, Ann Maria",""],
["hammond, ann maria","1598","Hammond, Ann Maria",""],
["hammond, ann maria","1706","Hammond, Ann Maria",""],
["hammond, antipas","556","Hammond, Antipas",""],
["hammond, arthur","548","Hammond, Arthur",""],
["hammond, arthur shelva","1768","Hammond, Arthur Shelva",""],
["hammond, asher porter","1375","Hammond, Asher Porter",""],
["hammond, baby","1757","Hammond, baby",""],
["hammond, barbara ann","398","Hammond, Barbara Ann",""],
["hammond, barnabas","489","Hammond, Barnabas",""],
["hammond, barnabas","500","Hammond, Barnabas",""],
["hammond, barnabas","515","Hammond, Barnabas",""],
["hammond, bartimeus","1325","Hammond, bartimeus",""],
["hammond, barzillai","557","Hammond, Barzillai",""],
["hammond, benjamin","412","Hammond, Benjamin",""],
["hammond, benjamin","422","Hammond, Benjamin",""],
["hammond, benjamin","427","Hammond, Benjamin",""],
["hammond, benjamin","457","Hammond, Benjamin",""],
["hammond, benjamin","461","Hammond, Benjamin",""],
["hammond, benjamin","482","Hammond, Benjamin",""],
["hammond, benjamin","527","Hammond, Benjamin",""],
["hammond, benjamin","534","Hammond, Benjamin",""],
["hammond, benjamin","1623","Hammond, Benjamin",""],
["hammond, benjamin barnes","481","Hammond, Benjamin Barnes",""],
["hammond, benoni g","1328","Hammond, Benoni G",""],
["hammond, bethiah","541","Hammond, Bethiah",""],
["hammond, blanche","1657","Hammond, Blanche",""],
["hammond, breanna michelle","4","Hammond, Breanna Michelle",""],
["hammond, breanna michelle","1054","Hammond, Breanna Michelle",""],
["hammond, brooke nicole","51","Hammond, Brooke Nicole",""],
["hammond, calib","1504","Hammond, Calib",""],
["hammond, calvin","1502","Hammond, Calvin",""],
["hammond, calvin seavey","1744","Hammond, Calvin Seavey",""],
["hammond, caroline","1300","Hammond, Caroline",""],
["hammond, caroline augusta","1701","Hammond, Caroline Augusta",""],
["hammond, catherine m.","1687","Hammond, Catherine M.",""],
["hammond, catholine","1348","Hammond, Catholine",""],
["hammond, charles","1327","Hammond, charles",""],
["hammond, charles","1364","Hammond, Charles",""],
["hammond, charles","1367","Hammond, Charles",""],
["hammond, charles","1376","Hammond, Charles",""],
["hammond, charles","1628","Hammond, Charles",""],
["hammond, charles h","1752","Hammond, Charles H",""],
["hammond, charles m","1755","Hammond, Charles M",""],
["hammond, charles moses","1646","Hammond, Charles Moses",""],
["hammond, charlote","415","Hammond, Charlote",""],
["hammond, charlotte","1669","Hammond, Charlotte",""],
["hammond, charlotte eliza","1693","Hammond, Charlotte Eliza",""],
["hammond, child","195","Hammond, Child",""],
["hammond, child","1763","Hammond, child",""],
["hammond, chloe","1728","Hammond, Chloe",""],
["hammond, chris","58","Hammond, Chris",""],
["hammond, christopher j","907","Hammond, Christopher J",""],
["hammond, christopher james","1","Hammond, Christopher James",""],
["hammond ii, christopher james","5","Hammond II, Christopher James",""],
["hammond ii, christopher james","1053","Hammond II, Christopher James",""],
["hammond, clarence m.","1722","Hammond, Clarence M.",""],
["hammond, clarissa clara","1334","Hammond, Clarissa Clara",""],
["hammond, clark j.","1739","Hammond, Clark J.",""],
["hammond, clyde","186","HAMMOND, Clyde",""],
["hammond, consider morgan","1339","Hammond, Consider Morgan",""],
["hammond, cora ann","1756","Hammond, Cora Ann",""],
["hammond, cyrus","1292","Hammond, Cyrus",""],
["hammond, dakota mae","2","Hammond, Dakota Mae",""],
["hammond, daniel","473","Hammond, Daniel",""],
["hammond, daniel","474","Hammond, Daniel",""],
["hammond, daniel","1307","Hammond, Daniel",""],
["hammond, david","1627","Hammond, David",""],
["hammond, deborah","1674","Hammond, Deborah",""],
["hammond, dennis fletcher","1696","Hammond, Dennis Fletcher",""],
["hammond, dewitt clinton","1370","Hammond, Dewitt Clinton",""],
["hammond, donald k","1770","Hammond, Donald K",""],
["hammond, donny","1761","Hammond, Donny",""],
["hammond, doras","1282","Hammond, Doras",""],
["hammond, dorothy l","29","Hammond, Dorothy L",""],
["hammond, dulcina","1264","Hammond, Dulcina",""],
["hammond, ebenezer","1660","Hammond, Ebenezer",""],
["hammond, ebenezer","1663","Hammond, Ebenezer",""],
["hammond, ebnezar","1688","Hammond, Ebnezar",""],
["hammond, edmister","518","Hammond, Edmister",""],
["hammond, edward","1608","Hammond, Edward",""],
["hammond, edward marcellus","1709","Hammond, Edward Marcellus",""],
["hammond, eliakim","469","Hammond, Eliakim",""],
["hammond, elihue","1263","Hammond, Elihue",""],
["hammond, elijah","1507","Hammond, Elijah",""],
["hammond, elisa a.","1715","Hammond, Elisa A.",""],
["hammond, elisha","555","Hammond, Elisha",""],
["hammond, elisha","1668","Hammond, Elisha",""],
["hammond, elisha quincy","1694","Hammond, Elisha Quincy",""],
["hammond, elizabeth","544","Hammond, Elizabeth",""],
["hammond, elizabeth","565","Hammond, Elizabeth",""],
["hammond, elizabeth","576","Hammond, Elizabeth",""],
["hammond, elizabeth","584","Hammond, Elizabeth",""],
["hammond, elizabeth","607","Hammond, Elizabeth",""],
["hammond, elizabeth","1333","Hammond, Elizabeth",""],
["hammond, elizabeth","1338","Hammond, Elizabeth",""],
["hammond, elizabeth","1349","Hammond, Elizabeth",""],
["hammond, elizabeth","1606","Hammond, Elizabeth",""],
["hammond, elizabeth","1667","Hammond, Elizabeth",""],
["hammond, elizabeth","1670","Hammond, Elizabeth",""],
["hammond, elizabeth","1673","Hammond, Elizabeth",""],
["hammond, elizabeth j","1354","Hammond, Elizabeth J",""],
["hammond, elizabeth paine","831","Hammond, Elizabeth Paine",""],
["hammond, ellen","1651","Hammond, Ellen",""],
["hammond, ellen m.","1713","Hammond, Ellen M.",""],
["hammond, elnathan","535","Hammond, Elnathan",""],
["hammond, emma","416","Hammond, Emma",""],
["hammond, emmor","1288","Hammond, Emmor",""],
["hammond, ephraim","1727","Hammond, Ephraim",""],
["hammond, ermina seraph","1641","Hammond, Ermina Seraph",""],
["hammond, esther","1361","Hammond, Esther",""],
["hammond, esther","1656","Hammond, Esther",""],
["hammond, ethel","1765","Hammond, Ethel",""],
["hammond, eunice","1261","Hammond, Eunice",""],
["hammond, eunice","1272","Hammond, Eunice",""],
["hammond, eunice","1740","Hammond, Eunice",""],
["hammond, fannie","1631","Hammond, Fannie",""],
["hammond, fear","435","Hammond, Fear",""],
["hammond, fear","1315","Hammond, Fear",""],
["hammond, fern","1764","Hammond, Fern",""],
["hammond, frances","410","Hammond, Frances",""],
["hammond, frances arlett","1745","Hammond, Frances Arlett",""],
["hammond, frances c","211","HAMMOND, Frances C",""],
["hammond, frances carolyn","28","HAMMOND, Frances Carolyn",""],
["hammond, frank","420","Hammond, Frank",""],
["hammond, frank l","1767","Hammond, Frank L",""],
["hammond, frank leslie","1754","Hammond, Frank Leslie",""],
["hammond, franklin","1747","Hammond, Franklin",""],
["hammond, freeman","1262","Hammond, Freeman",""],
["hammond, george","1506","Hammond, George",""],
["hammond, george boyden","1642","Hammond, George Boyden",""],
["hammond, george francis","1766","Hammond, George Francis",""],
["hammond, george peter","1707","Hammond, George Peter",""],
["hammond, george w.","1601","Hammond, George W.",""],
["hammond, grace l","1654","Hammond, Grace L",""],
["hammond, hammond m","188","HAMMOND, Hammond M",""],
["hammond, hannah","424","Hammond, Hannah",""],
["hammond, hannah","466","Hammond, Hannah",""],
["hammond, hannah","1280","Hammond, Hannah",""],
["hammond, hannah","1650","Hammond, Hannah",""],
["hammond, hannah frances","1643","Hammond, Hannah Frances",""],
["hammond, harriette marie","1692","Hammond, Harriette Marie",""],
["hammond, harry","418","Hammond, Harry",""],
["hammond, harry t","1356","Hammond, Harry T",""],
["hammond, harry w","1759","Hammond, Harry W",""],
["hammond, hattie may","1655","Hammond, Hattie May",""],
["hammond, henry","392","Hammond, Henry",""],
["hammond, henry","611","Hammond, Henry",""],
["hammond, henry","616","Hammond, Henry",""],
["hammond, henry","1260","Hammond, Henry",""],
["hammond, henry","1710","Hammond, Henry",""],
["hammond, herman foster","22","Hammond, Herman Foster",""],
["hammond, hezekiah m","1342","Hammond, Hezekiah M",""],
["hammond, howard l","1758","Hammond, Howard L",""],
["hammond, hugh","1725","Hammond, Hugh",""],
["hammond, innocent","514","Hammond, Innocent",""],
["hammond, ira","1336","Hammond, Ira",""],
["hammond, isaac","468","Hammond, Isaac",""],
["hammond, isaac","1289","Hammond, Isaac",""],
["hammond, israel","561","Hammond, Israel",""],
["hammond, iva","419","Hammond, Iva",""],
["hammond, jabez","451","HAMMOND, Jabez",""],
["hammond, jabez","539","Hammond, Jabez",""],
["hammond, jabez","748","Hammond, Jabez",""],
["hammond, jabez","1505","Hammond, Jabez",""],
["hammond, jacob","1281","Hammond, Jacob",""],
["hammond, jacob b","1306","Hammond, Jacob B",""],
["hammond, jacob troy","53","Hammond, Jacob Troy",""],
["hammond, james","414","Hammond, James",""],
["hammond, james","1290","Hammond, James",""],
["hammond, james h.","1714","Hammond, James H.",""],
["hammond, james henry","1690","Hammond, James Henry",""],
["hammond, james henry","1699","Hammond, James Henry",""],
["hammond, james lewis","1645","Hammond, James Lewis",""],
["hammond, jane","1634","Hammond, Jane",""],
["hammond, jane a.","1712","Hammond, Jane A.",""],
["hammond, jane l","1371","Hammond, Jane L",""],
["hammond, jean","604","Hammond, Jean",""],
["hammond, jean","612","Hammond, Jean",""],
["hammond, jedediah","491","Hammond, Jedediah",""],
["hammond, jedediah","507","Hammond, Jedediah",""],
["hammond, jedidah","486","Hammond, Jedidah",""],
["hammond, jedidah","492","Hammond, Jedidah",""],
["hammond, jedidah","493","Hammond, Jedidah",""],
["hammond, jeduthan","499","Hammond, Jeduthan",""],
["hammond, jeduthan","1737","Hammond, Jeduthan",""],
["hammond, jefferson","1658","Hammond, Jefferson",""],
["hammond, jemima","1269","Hammond, Jemima",""],
["hammond, jenetty","1277","Hammond, Jenetty",""],
["hammond, jennie marion","1644","Hammond, Jennie Marion",""],
["hammond, joan","606","HAMMOND, Joan",""],
["hammond, joannah","1665","Hammond, Joannah",""],
["hammond, johane","602","Hammond, Johane",""],
["hammond, johanna","626","Hammond, Johanna",""],
["hammond, johanna","632","HAMMOND, Johanna",""],
["hammond, johanna","638","HAMMOND, Johanna",""],
["hammond, john","436","Hammond, John",""],
["hammond, john","479","Hammond, John",""],
["hammond, john","483","Hammond, John",""],
["hammond, john","503","Hammond, John",""],
["hammond, john","510","Hammond, John",""],
["hammond, john","546","Hammond, john",""],
["hammond, john","563","Hammond, John",""],
["hammond, john","568","Hammond, John",""],
["hammond iii, john","601","Hammond III, John",""],
["hammond, john","617","Hammond, John",""],
["hammond ii, john","624","Hammond II, John",""],
["hammond, john","630","Hammond, John",""],
["hammond, john","633","Hammond, John",""],
["hammond, john","634","Hammond, John",""],
["hammond, john","637","Hammond, John",""],
["hammond, john","639","Hammond, John",""],
["hammond, john","640","Hammond, John",""],
["hammond, john","641","Hammond, John",""],
["hammond, john","648","Hammond, John",""],
["hammond, john","1258","Hammond, John",""],
["hammond, john","1285","Hammond, John",""],
["hammond, john","1313","Hammond, John",""],
["hammond, john","1729","Hammond, John",""],
["hammond, john","1738","Hammond, John",""],
["hammond, john arnold","537","Hammond, John Arnold",""],
["hammond, john d","27","Hammond, John D",""],
["hammond, john dennis","1704","Hammond, John Dennis",""],
["hammond, john f","1359","Hammond, John F",""],
["hammond, john fox","1700","Hammond, John Fox",""],
["hammond, john l","1363","Hammond, John L",""],
["hammond, john s.","1718","Hammond, John S.",""],
["hammond, jonathan john","526","Hammond, Jonathan John",""],
["hammond, jonet","1774","Hammond, Jonet",""],
["hammond, jonet","1776","HAMMOND, Jonet",""],
["hammond, jon michael","13","Hammond, Jon Michael",""],
["hammond, joseph","1624","Hammond, Joseph",""],
["hammond, joseph","1632","Hammond, Joseph",""],
["hammond, joseph","1736","Hammond, Joseph",""],
["hammond b1713, grandfather of capt stephen, josephus","558","Hammond B1713, grandfather of Capt Stephen, Josephus",""],
["hammond, joshua","1499","Hammond, Joshua",""],
["hammond, josiah","488","Hammond, Josiah",""],
["hammond, lany","1360","Hammond, Lany",""],
["hammond, lany","1362","Hammond, Lany",""],
["hammond, laura m","873","Hammond, Laura M",""],
["hammond, laura michelle","12","Hammond, Laura Michelle",""],
["hammond, lauren mackenna","52","Hammond, Lauren Mackenna",""],
["hammond, levern","417","Hammond, Levern",""],
["hammond, levi","1255","Hammond, Levi",""],
["hammond, levina louisa","445","Hammond, Levina Louisa",""],
["hammond, lewis","1302","Hammond, Lewis",""],
["hammond, lewis p","1347","Hammond, Lewis P",""],
["hammond, lillie f.","1723","Hammond, Lillie F.",""],
["hammond, lincoln","1653","Hammond, Lincoln",""],
["hammond, lois","1274","Hammond, Lois",""],
["hammond, lothrop","1500","Hammond, Lothrop",""],
["hammond, louisa","407","Hammond, Louisa",""],
["hammond, louisa","1278","Hammond, Louisa",""],
["hammond, lucinda","1344","Hammond, Lucinda",""],
["hammond, lucy","516","Hammond, Lucy",""],
["hammond, lucy","1283","Hammond, Lucy",""],
["hammond, luke","750","Hammond, Luke",""],
["hammond, luthan","465","Hammond, Luthan",""],
["hammond, luther","1503","Hammond, Luther",""],
["hammond, lydia","498","Hammond, Lydia",""],
["hammond, lydia","1293","Hammond, Lydia",""],
["hammond, lydia","1619","Hammond, Lydia",""],
["hammond, lydia","1637","Hammond, Lydia",""],
["hammond, lydia ann","1353","Hammond, Lydia Ann",""],
["hammond, lydia antoinette","1691","Hammond, Lydia Antoinette",""],
["hammond, mahalia","1320","Hammond, mahalia",""],
["hammond, marcus claudius marcellus","1686","Hammond, Marcus Claudius Marcellus",""],
["hammond, marcus claudius marcellus","1698","Hammond, Marcus Claudius Marcellus",""],
["hammond, margaret","605","Hammond, Margaret",""],
["hammond, margaret","619","Hammond, Margaret",""],
["hammond, margaret ann burke","10","Hammond, Margaret Ann Burke",""],
["hammond, maria","447","Hammond, Maria",""],
["hammond, maria","464","Hammond, Maria",""],
["hammond, maria","490","Hammond, Maria",""],
["hammond, maria","504","Hammond, Maria",""],
["hammond, maria","749","Hammond, Maria",""],
["hammond, maria","1291","Hammond, Maria",""],
["hammond, maria","1346","Hammond, Maria",""],
["hammond, maria e","1298","Hammond, Maria E",""],
["hammond, maria loretta","1636","Hammond, Maria Loretta",""],
["hammond, mariby","403","Hammond, Mariby",""],
["hammond, marie","588","Hammond, Marie",""],
["hammond, marie","592","Hammond, Marie",""],
["hammond, marie sarah","564","HAMMOND, Marie Sarah",""],
["hammond, marietta","1373","Hammond, Marietta",""],
["hammond, marjori","627","Hammond, Marjori",""],
["hammond, mark","1621","Hammond, Mark",""],
["hammond, martha","586","Hammond, Martha",""],
["hammond, martha","587","Hammond, Martha",""],
["hammond, martha","591","Hammond, Martha",""],
["hammond, martha","594","Hammond, Martha",""],
["hammond, martha a","1750","Hammond, Martha A",""],
["hammond, marthaline","1384","Hammond, Marthaline",""],
["hammond, marthaline","1603","Hammond, Marthaline",""],
["hammond, mary","462","Hammond, Mary",""],
["hammond, mary","471","Hammond, Mary",""],
["hammond, mary","501","Hammond, Mary",""],
["hammond, mary","523","Hammond, Mary",""],
["hammond, mary","530","Hammond, Mary",""],
["hammond, mary","543","Hammond, Mary",""],
["hammond, mary","562","Hammond, Mary",""],
["hammond, mary","1259","Hammond, Mary",""],
["hammond, mary","1271","Hammond, Mary",""],
["hammond, mary","1319","Hammond, mary",""],
["hammond, mary","1731","Hammond, Mary",""],
["hammond, mary a","408","Hammond, Mary A",""],
["hammond, mary adelia","1639","Hammond, Mary Adelia",""],
["hammond, mary bell","545","Hammond, Mary Bell",""],
["hammond, mary catherine","1711","Hammond, Mary Catherine",""],
["hammond, mary elizabeth","1355","Hammond, Mary Elizabeth",""],
["hammond, mary f.","1626","Hammond, Mary F.",""],
["hammond, mary maude","187","Hammond, Mary Maude",""],
["hammond, maryone","625","Hammond, Maryone",""],
["hammond, matilda","1332","Hammond, Matilda",""],
["hammond, meganandtrey","878","Hammond, MeganandTrey",""],
["hammond, mehitable","1734","Hammond, Mehitable",""],
["hammond, melintha","1256","Hammond, Melintha",""],
["hammond, meribah","402","Hammond, Meribah",""],
["hammond, meribah","423","Hammond, Meribah",""],
["hammond, meribah","432","Hammond, Meribah",""],
["hammond, meribah","1311","Hammond, Meribah",""],
["hammond, millard arvine","1647","Hammond, Millard Arvine",""],
["hammond, minerva j hoisington","26","Hammond, Minerva J Hoisington",""],
["hammond, nancy","1296","Hammond, Nancy",""],
["hammond, nancy j","396","Hammond, Nancy J",""],
["hammond, naomi","1322","Hammond, naomi",""],
["hammond, nathan","525","Hammond, Nathan",""],
["hammond, nathan","536","Hammond, Nathan",""],
["hammond, nathan","552","Hammond, Nathan",""],
["hammond, nathaniel","614","Hammond, Nathaniel",""],
["hammond, nathaniel","1268","Hammond, Nathaniel",""],
["hammond, nelson","1305","Hammond, Nelson",""],
["hammond, nina bell","189","Hammond, Nina Bell",""],
["hammond, octavia susan","1705","Hammond, Octavia Susan",""],
["hammond, orlando","1746","Hammond, Orlando",""],
["hammond, othniel","502","Hammond, Othniel",""],
["hammond, pardon","1616","Hammond, Pardon",""],
["hammond, patience","1661","Hammond, Patience",""],
["hammond, patrick john","25","Hammond, Patrick John",""],
["hammond, paul","456","Hammond, Paul",""],
["hammond, paul","505","Hammond, Paul",""],
["hammond, paul jr","1326","Hammond, Paul Jr",""],
["hammond, phebe","497","Hammond, Phebe",""],
["hammond, philip","615","Hammond, Philip",""],
["hammond, philip harvey","1379","Hammond, Philip Harvey",""],
["hammond, philip harvey","1600","Hammond, Philip Harvey",""],
["hammond, pickens t.","1719","Hammond, Pickens T.",""],
["hammond, polly","1343","Hammond, Polly",""],
["hammond, polly","1618","Hammond, Polly",""],
["hammond, polypus","559","Hammond, Polypus",""],
["hammond, prince","444","Hammond, Prince",""],
["hammond, prince","478","HAMMOND, Prince",""],
["hammond, priscilla","517","Hammond, Priscilla",""],
["hammond, prudence","603","Hammond, Prudence",""],
["hammond, ralph","651","Hammond, Ralph",""],
["hammond, rebecca","433","Hammond, Rebecca",""],
["hammond, rebecca","1257","Hammond, Rebecca",""],
["hammond, rebecca","1312","Hammond, Rebecca",""],
["hammond, reuben l.","192","Hammond, Reuben L.",""],
["hammond, robert","628","Hammond, Robert",""],
["hammond, robert j","212","HAMMOND, Robert J",""],
["hammond, robert john","20","Hammond, Robert John",""],
["hammond iii, robert john","57","Hammond III, Robert John",""],
["hammond, robert michael","9","Hammond, Robert Michael",""],
["hammond, roger","560","Hammond, Roger",""],
["hammond, roland","538","Hammond, Roland",""],
["hammond, rosalis robles","8","Hammond, Rosalis Robles",""],
["hammond, rosamond","485","Hammond, Rosamond",""],
["hammond, rose","521","Hammond, Rose",""],
["hammond, rose","524","Hammond, Rose",""],
["hammond, rose","593","Hammond, Rose",""],
["hammond, rose","1730","Hammond, Rose",""],
["hammond, ruth","463","Hammond, Ruth",""],
["hammond, ruth","581","Hammond, Ruth",""],
["hammond, ruth","1273","Hammond, Ruth",""],
["hammond, ruth","1324","Hammond, ruth",""],
["hammond, ruth","1762","Hammond, Ruth",""],
["hammond, salathiel","477","Hammond, Salathiel",""],
["hammond, salley","1671","Hammond, Salley",""],
["hammond, samuel","411","Hammond, Samuel",""],
["hammond, samuel","443","Hammond, Samuel",""],
["hammond, samuel","448","Hammond, Samuel",""],
["hammond, samuel","470","Hammond, Samuel",""],
["hammond ii, samuel","487","Hammond II, Samuel",""],
["hammond, samuel","512","Hammond, Samuel",""],
["hammond, samuel","1267","Hammond, Samuel",""],
["hammond, samuel","1303","Hammond, Samuel",""],
["hammond, samuel","1323","Hammond, samuel",""],
["hammond, samuel (iii)","522","Hammond, Samuel (III)",""],
["hammond, samuel d","1358","Hammond, Samuel D",""],
["hammond, sarah","391","Hammond, Sarah",""],
["hammond, sarah","459","Hammond, Sarah",""],
["hammond, sarah","540","Hammond, Sarah",""],
["hammond, sarah","547","Hammond, Sarah",""],
["hammond, sarah","551","Hammond, Sarah",""],
["hammond, sarah","575","HAMMOND, Sarah",""],
["hammond, sarah","1321","Hammond, sarah",""],
["hammond, sarah","1664","Hammond, Sarah",""],
["hammond, sarah (sally)","1633","Hammond, Sarah (Sally)",""],
["hammond, sarah ann","1382","Hammond, Sarah Ann",""],
["hammond, sarah ann","1599","Hammond, Sarah Ann",""],
["hammond, saraph","1630","Hammond, Saraph",""],
["hammond, schabod c","1751","Hammond, Schabod C",""],
["hammond, seth","484","Hammond, Seth",""],
["hammond, seth","520","Hammond, Seth",""],
["hammond iv, sir john","583","Hammond IV, Sir John",""],
["hammond, sir robert","1596","Hammond, Sir Robert",""],
["hammond, sir william","529","Hammond, Sir William",""],
["hammond, sommerfield george","1689","Hammond, Sommerfield George",""],
["hammond, son","196","Hammond, Son",""],
["hammond, sophia","1629","Hammond, Sophia",""],
["hammond, sophronia w","1749","Hammond, Sophronia W",""],
["hammond, spencer","1735","Hammond, Spencer",""],
["hammond, stanley","1369","Hammond, Stanley",""],
["hammond, stephen","1266","Hammond, Stephen",""],
["hammond, susan","590","Hammond, Susan",""],
["hammond, susan","1270","Hammond, Susan",""],
["hammond, susan","1297","Hammond, Susan",""],
["hammond, susan","1622","Hammond, Susan",""],
["hammond, susannah","549","Hammond, Susannah",""],
["hammond, susannah","553","Hammond, Susannah",""],
["hammond, sylvester olmstead","1372","Hammond, Sylvester Olmstead",""],
["hammond, thankful","476","HAMMOND, Thankful",""],
["hammond, theodosia","1708","Hammond, Theodosia",""],
["hammond, thomas","431","Hammond, Thomas",""],
["hammond, thomas","446","Hammond, Thomas",""],
["hammond, thomas","467","Hammond, Thomas",""],
["hammond, thomas","566","Hammond, Thomas",""],
["hammond, thomas","571","Hammond, Thomas",""],
["hammond, thomas","574","Hammond, Thomas",""],
["hammond, thomas","589","Hammond, Thomas",""],
["hammond, thomas","597","Hammond, Thomas",""],
["hammond, thomas","599","Hammond, Thomas",""],
["hammond, thomas","646","Hammond, Thomas",""],
["hammond, thomas","650","Hammond, Thomas",""],
["hammond, thomas","1253","Hammond, Thomas",""],
["hammond, thomas,","747","Hammond, Thomas,",""],
["hammond, thomas jefferson","1635","Hammond, Thomas Jefferson",""],
["hammond, tibod","1773","Hammond, Tibod",""],
["hammond, tibod","1775","HAMMOND, Tibod",""],
["hammond, timothy james","24","Hammond, Timothy James",""],
["hammond, viola may","194","HAMMOND, Viola May",""],
["hammond, walter f.","1716","Hammond, Walter F.",""],
["hammond, william","413","Hammond, William",""],
["hammond, william","437","Hammond, William",""],
["hammond, william","450","Hammond, William",""],
["hammond, william","458","Hammond, William",""],
["hammond, william","472","Hammond, william",""],
["hammond, william","570","Hammond, William",""],
["hammond, william","580","Hammond, William",""],
["hammond, william","609","Hammond, William",""],
["hammond, william","618","Hammond, William",""],
["hammond, william","653","Hammond, William",""],
["hammond, william","1295","Hammond, William",""],
["hammond, william","1314","Hammond, William",""],
["hammond, william","1335","Hammond, William",""],
["hammond, william","1357","Hammond, William",""],
["hammond, william","1365","Hammond, William",""],
["hammond, william","1607","Hammond, William",""],
["hammond, william","1610","Hammond, William",""],
["hammond, william","1612","Hammond, William",""],
["hammond, william","1614","Hammond, William",""],
["hammond, william","1620","Hammond, William",""],
["hammond, william","1652","Hammond, William",""],
["hammond, william charles","1329","Hammond, William Charles",""],
["hammond, william e.","1717","Hammond, William E.",""],
["hammond, william jefferson","1640","Hammond, William Jefferson",""],
["hammond, william meredith","1695","Hammond, William Meredith",""],
["hammond, william robinson","1703","Hammond, William Robinson",""],
["hammond, william wallace","1374","Hammond, William Wallace",""],
["hammond, william wallace","1383","Hammond, William Wallace",""],
["hammond, william wallace","1602","Hammond, William Wallace",""],
["hammond, wilson","1748","Hammond, Wilson",""],
["hammond, zephaniah","519","Hammond, Zephaniah",""],
["hammond, zephaniah","1275","Hammond, Zephaniah",""],
["hammond, zina","1254","Hammond, Zina",""],
["hammond, zoath","393","Hammond, Zoath",""],
["hammond, zoath","395","Hammond, Zoath",""],
["hammond, zoath","401","Hammond, Zoath",""],
["hammond, zoath w","409","Hammond, Zoath W",""],
["hammond, zoeth","399","Hammond, Zoeth",""],
["hammond, zoeth","1316","Hammond, Zoeth",""],
["hammond,, robert john ii","19","Hammond,, Robert John II",""],
["hammond boyles, amanda","59","Hammond Boyles, Amanda",""],
["hammond de pulford, sir knight robert","1772","Hammond de Pulford, Sir Knight Robert",""],
["hammonde, maryone","631","Hammonde, Maryone",""],
["hammonde, maryone","636","Hammonde, Maryone",""],
["hammond kelsey, johane","585","Hammond Kelsey, Johane",""],
["hamond, robert","610","Hamond, Robert",""],
["hamonde, johanna","635","Hamonde, Johanna",""],
["hart, mary","1010","Hart, Mary",""],
["haskel, elizabeth","1659","Haskel, Elizabeth",""],
["hathaway, abraham","1435","Hathaway, Abraham",""],
["hathaway, agnes","1434","Hathaway, Agnes",""],
["hathaway, anthony","1436","Hathaway, Anthony",""],
["hathaway, arthur","495","HATHAWAY, Arthur",""],
["hathaway, arthur","793","Hathaway, Arthur",""],
["hathaway, arthur","794","Hathaway, Arthur",""],
["hathaway, arthur","807","Hathaway, Arthur",""],
["hathaway, arthur","1385","Hathaway, Arthur",""],
["hathaway, dan","799","Hathaway, Dan",""],
["hathaway, elizabeth","1439","Hathaway, Elizabeth",""],
["hathaway, giles","1441","Hathaway, Giles",""],
["hathaway, hannah","795","Hathaway, Hannah",""],
["hathaway, hannah","804","Hathaway, Hannah",""],
["hathaway, hannah","1389","Hathaway, Hannah",""],
["hathaway, john","797","Hathaway, John",""],
["hathaway, jonathan","800","Hathaway, Jonathan",""],
["hathaway, jonathan","803","Hathaway, Jonathan",""],
["hathaway, lydia","796","Hathaway, Lydia",""],
["hathaway, mary","442","Hathaway, Mary",""],
["hathaway, mary","1390","Hathaway, Mary",""],
["hathaway, mary","1437","Hathaway, Mary",""],
["hathaway, matthew","1440","Hathaway, Matthew",""],
["hathaway, nicholas","1438","Hathaway, Nicholas",""],
["hathaway, richard","801","Hathaway, Richard",""],
["hathaway, sarah","798","Hathaway, Sarah",""],
["hathaway, sarah","1442","Hathaway, Sarah",""],
["hathaway, susannah","1386","Hathaway, Susannah",""],
["hathaway, thomas","802","Hathaway, Thomas",""],
["hathaway jr, thomas","1388","HATHAWAY Jr, THOMAS",""],
["hathaway, thomas","1391","Hathaway, Thomas",""],
["haward, constance","1491","Haward, Constance",""],
["hoisington, barzava zebulon","200","Hoisington, Barzava Zebulon",""],
["hoisington, charles","340","HOISINGTON, Charles",""],
["hoisington, israel","206","Hoisington, Israel",""],
["hoisington, jesse k","337","Hoisington, Jesse K",""],
["hoisington, joab","342","Hoisington, Joab",""],
["hoisington, lewis henry","338","HOISINGTON, Lewis Henry",""],
["hoisington, louisa","336","Hoisington, Louisa",""],
["hoisington, martha","205","Hoisington, Martha",""],
["hoisington, martha j","339","HOISINGTON, Martha J",""],
["hoisington, mary","202","Hoisington, Mary",""],
["hoisington, samuel","198","Hoisington, Samuel",""],
["hoisington, sarah ann","204","Hoisington, Sarah Ann",""],
["hoisington, william","203","Hoisington, William",""],
["holbrook, estela","1059","Holbrook, Estela",""],
["holbrook, eunice","1060","Holbrook, Eunice",""],
["holbrook, orson l","1061","Holbrook, Orson L",""],
["holbrook, royal h","1056","Holbrook, Royal H",""],
["holbrook, silas p","1057","Holbrook, Silas P",""],
["holbrook, una","1058","Holbrook, Una",""],
["hoskins, anne","1123","Hoskins, Anne",""],
["hoysington, peter","201","Hoysington, Peter",""],
["hughes, martha","149","Hughes, Martha",""],
["hunnewell, elizabeth","554","Hunnewell, Elizabeth",""],
["hutchens, john","1203","Hutchens, John",""],
["hutchens, joseph","1211","Hutchens, Joseph",""],
["hutchens, mary","1213","Hutchens, Mary",""],
["hutchens, silas","1214","Hutchens, Silas",""],
["hutchings, daniel","1225","Hutchings, Daniel",""],
["hutchins, abigail","274","Hutchins, Abigail",""],
["hutchins, abigail","1208","Hutchins, Abigail",""],
["hutchins, anne","1216","Hutchins, Anne",""],
["hutchins, benjamin","1205","Hutchins, Benjamin",""],
["hutchins, benjamin","1232","Hutchins, Benjamin",""],
["hutchins, darius","1196","Hutchins, Darius",""],
["hutchins, daughter","1207","Hutchins, daughter",""],
["hutchins, elizabeth","1192","Hutchins, Elizabeth",""],
["hutchins, elizabeth","1221","Hutchins, Elizabeth",""],
["hutchins, elizabeth","1230","Hutchins, Elizabeth",""],
["hutchins, elizabeth","1235","Hutchins, Elizabeth",""],
["hutchins, ezra","295","HUTCHINS, Ezra",""],
["hutchins, ezra","1199","Hutchins, Ezra",""],
["hutchins, hannah","1194","Hutchins, Hannah",""],
["hutchins, john","1191","HUTCHINS, John",""],
["hutchins, john","1218","Hutchins, John",""],
["hutchins, joseph","1220","Hutchins, Joseph",""],
["hutchins, joseph","1229","Hutchins, Joseph",""],
["hutchins, joshua","1204","Hutchins, Joshua",""],
["hutchins, karen","1236","Hutchins, Karen",""],
["hutchins, keziah","1212","Hutchins, Keziah",""],
["hutchins, love","1231","Hutchins, Love",""],
["hutchins, mary","1219","Hutchins, Mary",""],
["hutchins, nicholas","1201","Hutchins, Nicholas",""],
["hutchins, penuel","1198","Hutchins, Penuel",""],
["hutchins, ruth","1210","Hutchins, Ruth",""],
["hutchins, samuel","1233","Hutchins, Samuel",""],
["hutchins, sarah","1206","Hutchins, Sarah",""],
["hutchins, shubael","1195","Hutchins, Shubael",""],
["hutchins, sybil","1197","Hutchins, Sybil",""],
["hutchins, thomas","1223","Hutchins, Thomas",""],
["hutchins, thomas","1224","Hutchins, Thomas",""],
["hutchins, william","1226","Hutchins, William",""],
["hutchins, william","1227","Hutchins, William",""],
["hutchins, william","1234","Hutchins, William",""],
["hutchins, william","1237","Hutchins, William",""],
["hutchins, wyman","1215","Hutchins, Wyman",""],
["hutchins, zerviah","1193","Hutchins, Zerviah",""],
["i, sarah warren","1412","I, Sarah Warren",""],
["isham, mira dorcus","1121","Isham, Mira Dorcus",""],
["jimenez medina, nellive","865","Jimenez Medina, Nellive",""],
["jimenez mola, eloi","871","Jimenez Mola, Eloi",""],
["johne, johanna","600","Johne, Johanna",""],
["johne, johanna","629","Johne, Johanna",""],
["johnson, mary","1308","Johnson, Mary",""],
["jordan, mary ann","406","Jordan, Mary Ann",""],
["josiah, sr foster","1092","Josiah, Sr Foster",""],
["jouatt, elizabeth","1393","Jouatt, Elizabeth",""],
["kee, sarah","310","Kee, Sarah",""],
["kee, stewart","298","Kee, Stewart",""],
["keeble, emma proveth","642","Keeble, Emma Proveth",""],
["keeble, john thomas","644","Keeble, John Thomas",""],
["keeble, walter harry","643","Keeble, Walter Harry",""],
["kele","774","Kele",""],
["kendrick, alexander franklin","1043","Kendrick, Alexander Franklin",""],
["kendrick, annie budd","674","Kendrick, Annie Budd",""],
["kendrick, bessie m","15","Kendrick, Bessie M",""],
["kendrick, elizabeth caroline","1040","Kendrick, Elizabeth Caroline",""],
["kendrick, hazel bessie","14","Kendrick, Hazel Bessie",""],
["kendrick, james","1044","Kendrick, James",""],
["kendrick, james","1047","Kendrick, James",""],
["kendrick, john","1037","Kendrick, John",""],
["kendrick, john a.","1046","Kendrick, John A.",""],
["kendrick, john g","678","Kendrick, John G",""],
["kendrick, john smith","682","Kendrick, John Smith",""],
["kendrick, john william","673","Kendrick, John William",""],
["kendrick, julia ann","1038","Kendrick, Julia Ann",""],
["kendrick, m. smith","671","Kendrick, M. Smith",""],
["kendrick, mary","1042","Kendrick, Mary",""],
["kendrick, mary polly","1238","Kendrick, Mary Polly",""],
["kendrick, thaddeus","1041","Kendrick, Thaddeus",""],
["kendrick, vanderbilt","672","Kendrick, Vanderbilt",""],
["kendrick, william m","1039","Kendrick, William M",""],
["kendrick, william m","1045","Kendrick, William M",""],
["kerby, zilpha","1340","Kerby, Zilpha",""],
["key, ebenezer","299","Key, Ebenezer",""],
["key, hannah","291","Key, Hannah",""],
["keyes, abigail h","277","Keyes, Abigail H",""],
["keyes, amy spaulding","268","Keyes, Amy Spaulding",""],
["keyes, sarah louvira","262","Keyes, Sarah Louvira",""],
["keys, abigail h","281","Keys, Abigail H",""],
["keys, alma spalding","270","Keys, Alma Spalding",""],
["keys, ann l","37","Keys, Ann L",""],
["keys, bertha adele","248","Keys, Bertha Adele",""],
["keys, berton","264","Keys, Berton",""],
["keys, charlotte mary","43","Keys, Charlotte Mary",""],
["keys, clara eleanor","250","Keys, Clara Eleanor",""],
["keys, clarissa","263","Keys, Clarissa",""],
["keys, clarissa","280","Keys, Clarissa",""],
["keys, clarissa a","287","Keys, Clarissa A",""],
["keys, daniel","275","Keys, Daniel",""],
["keys, daniel hutchins","271","Keys, Daniel Hutchins",""],
["keys, dorothy maude","42","Keys, Dorothy Maude",""],
["keys, elisha","278","Keys, Elisha",""],
["keys, elisha","282","Keys, Elisha",""],
["keys, elisha day","283","Keys, Elisha Day",""],
["keys, eliza a","279","Keys, Eliza A",""],
["keys, eliza frances","259","Keys, Eliza Frances",""],
["keys, emma louise","252","Keys, Emma Louise",""],
["keys, estella althea","251","Keys, Estella Althea",""],
["keys, ezra hutchins","273","Keys, Ezra Hutchins",""],
["keys, ezra nelson","253","Keys, Ezra Nelson",""],
["keys, ezra nelson","265","Keys, Ezra Nelson",""],
["keys, florence mary","21","Keys, Florence Mary",""],
["keys, florence stella","241","Keys, Florence Stella",""],
["keys, florence stella","243","Keys, Florence Stella",""],
["keys, harlan page","245","Keys, Harlan Page",""],
["keys, helen lucille","38","Keys, Helen Lucille",""],
["keys, hellen l","46","Keys, Hellen L",""],
["keys, hiram","284","Keys, Hiram",""],
["keys, horace nelson","258","Keys, Horace Nelson",""],
["keys, horatio nelson","254","Keys, Horatio Nelson",""],
["keys, lawrence h","242","Keys, Lawrence H",""],
["keys, marietta","266","Keys, Marietta",""],
["keys, marietta beebe","269","Keys, Marietta Beebe",""],
["keys, mary","290","Keys, Mary",""],
["keys, mary elizabeth","36","Keys, Mary Elizabeth",""],
["keys, mary elizabeth","41","Keys, Mary Elizabeth",""],
["keys, nelson rowell","33","Keys, Nelson Rowell",""],
["keys, paphiras beebe","267","Keys, Paphiras Beebe",""],
["keys, pardon","289","Keys, Pardon",""],
["keys, rebecca","285","Keys, Rebecca",""],
["keys, robert nelson","39","Keys, Robert Nelson",""],
["keys, sara lomyra","261","Keys, Sara Lomyra",""],
["keys, shubael sherman","288","Keys, Shubael Sherman",""],
["keys, sidney bunce","249","Keys, Sidney Bunce",""],
["keys, silas day","260","Keys, Silas Day",""],
["keys, stephen powers","45","Keys, Stephen Powers",""],
["keys, willie a.","255","Keys, Willie A.",""],
["keys, willie aram","257","Keys, Willie Aram",""],
["kies, ebenezer kee","300","Kies, Ebenezer Kee",""],
["kies, wilson","304","Kies, Wilson",""],
["kindrick, coleman","681","Kindrick, Coleman",""],
["kindrick, lelita","680","Kindrick, Lelita",""],
["kindrick, oliver scruggs","669","Kindrick, Oliver Scruggs",""],
["kindrick, ramoth","679","Kindrick, Ramoth",""],
["kindrick, wesley","1049","Kindrick, Wesley",""],
["kingham, bathsheba elizabeth","772","Kingham, Bathsheba Elizabeth",""],
["kinney i, virginia magnolia","1724","Kinney I, Virginia Magnolia",""],
["lands, elizabeth","214","Lands, Elizabeth",""],
["lauzon","1392","Lauzon",""],
["lauzon, marie","792","Lauzon, Marie",""],
["leavens, abigail","294","Leavens, Abigail",""],
["le corbet, elizabeth","1778","LE CORBET, Elizabeth",""],
["lee, anna","958","Lee, Anna",""],
["lee, anne","216","Lee, Anne",""],
["lee, anne","977","Lee, Anne",""],
["lee, anney","973","Lee, Anney",""],
["lee, darkus","968","Lee, Darkus",""],
["lee, dorcas","947","Lee, Dorcas",""],
["lee, dorcus","954","Lee, Dorcus",""],
["lee, dorcus","960","Lee, Dorcus",""],
["lee, eleanor","976","Lee, Eleanor",""],
["lee, elizabeth","953","Lee, Elizabeth",""],
["lee, elizabeth","955","Lee, Elizabeth",""],
["lee, elizabeth","961","Lee, Elizabeth",""],
["lee, elizabeth","966","Lee, Elizabeth",""],
["lee, elizabeth","984","Lee, Elizabeth",""],
["lee, elizabeth","1016","Lee, Elizabeth",""],
["lee, fanny","970","Lee, Fanny",""],
["lee, frances","1032","Lee, Frances",""],
["lee, francis","1022","Lee, Francis",""],
["lee, francis","1034","Lee, Francis",""],
["lee, j. peterson","221","Lee, J. Peterson",""],
["lee, james","945","Lee, James",""],
["lee, james","963","Lee, James",""],
["lee, james","965","Lee, James",""],
["lee, james","972","Lee, James",""],
["lee, james","975","Lee, James",""],
["lee, james","978","Lee, James",""],
["lee, james","988","Lee, James",""],
["lee, james","992","lee, james",""],
["lee, james","995","lee, james",""],
["lee, james","997","lee, james",""],
["lee, james leigh","1001","Lee, James Leigh",""],
["lee, jeremiah  jerry ","950","Lee, Jeremiah  Jerry ",""],
["lee, jerry j.","220","Lee, Jerry J.",""],
["lee, john","986","Lee, John",""],
["lee, john","1011","Lee, John",""],
["lee, john","1012","Lee, John",""],
["lee, john watts","78","Lee, John Watts",""],
["lee, john watts","215","Lee, John Watts",""],
["lee, larkin","217","Lee, Larkin",""],
["lee, malinda","219","Lee, Malinda",""],
["lee, margaret","981","Lee, Margaret",""],
["lee, martha","980","Lee, Martha",""],
["lee, martha","985","Lee, Martha",""],
["lee, martha","991","Lee, Martha",""],
["lee, martha","994","Lee, Martha",""],
["lee, martha","996","Lee, Martha",""],
["lee, mary","974","Lee, Mary",""],
["lee, mary","990","Lee, Mary",""],
["lee, mary  polly ","956","Lee, Mary  Polly ",""],
["lee, mary polly","948","Lee, Mary Polly",""],
["lee, millie","1021","Lee, Millie",""],
["lee, milly","971","Lee, Milly",""],
["lee, nancy","944","Lee, Nancy",""],
["lee, nancy","957","Lee, Nancy",""],
["lee, rachel","982","Lee, Rachel",""],
["lee, rebeckah","979","Lee, Rebeckah",""],
["lee, rebeckah","993","Lee, Rebeckah",""],
["lee, richard","969","Lee, Richard",""],
["lee, richard w.","946","Lee, Richard W.",""],
["lee, robert","942","Lee, Robert",""],
["lee, robert","1002","Lee, Robert",""],
["lee, robert","1003","Lee, Robert",""],
["lee, robert","1006","Lee, Robert",""],
["lee, robert","1008","Lee, Robert",""],
["lee, samuel","1025","Lee, Samuel",""],
["lee, sarah","983","Lee, Sarah",""],
["lee, sarah","1020","Lee, Sarah",""],
["lee, susan","949","Lee, Susan",""],
["lee, susan","959","Lee, Susan",""],
["lee, susana","967","Lee, Susana",""],
["lee, thomas","1023","Lee, Thomas",""],
["lee, thomas","1033","Lee, Thomas",""],
["lee, william","218","Lee, William",""],
["lee, william","1004","Lee, William",""],
["lee, william","1005","Lee, William",""],
["lee, william","1007","Lee, William",""],
["lee, william","1009","Lee, William",""],
["lee, william","1035","Lee, William",""],
["lee, william f.","951","Lee, William F.",""],
["lee, willis isiah","952","Lee, Willis Isiah",""],
["lee leigh, sarah","1000","Lee Leigh, Sarah",""],
["lee lyonnell, lionell","1013","Lee Lyonnell, Lionell",""],
["leigh, elizabeth","1015","Leigh, Elizabeth",""],
["leigh, james","1018","Leigh, James",""],
["leigh, joseph","1014","Leigh, Joseph",""],
["leigh, patience","1019","Leigh, Patience",""],
["leigh, sarah","1017","Leigh, Sarah",""],
["leigh lee, henry","1027","Leigh Lee, Henry",""],
["lincoln, mary coffee","244","Lincoln, Mary Coffee",""],
["linscott, israel","1452","Linscott, Israel",""],
["linscott, susan","207","Linscott, Susan",""],
["little, thomas","1433","Little, Thomas",""],
["lnu, lucy","1568","Lnu, Lucy",""],
["lobdell, ruth","1352","Lobdell, Ruth",""],
["lothrop, sarah","1498","Lothrop, Sarah",""],
["lusher, joy waine","17","Lusher, Joy Waine",""],
["mackay, daniel","320","Mackay, Daniel",""],
["mackay, george","323","MacKay, George",""],
["mackay, jacob","317","Mackay, Jacob",""],
["mackay, mary","319","Mackay, Mary",""],
["mackay, nathaniel","321","Mackay, Nathaniel",""],
["mackay, sarah","322","Mackay, Sarah",""],
["mackey, david","311","Mackey, David",""],
["mackey, david","389","Mackey, David",""],
["mackey, james","313","Mackey, James",""],
["mackey, james","378","MACKEY, James",""],
["mackey, john","377","Mackey, John",""],
["mackey, john","383","Mackey, John",""],
["mackey, katherine","381","MACKEY, Katherine",""],
["mackey, katherine","388","MACKEY, Katherine",""],
["mackey, mary","328","Mackey, Mary",""],
["mackey, mary","329","MacKey, Mary",""],
["mackey, neale","384","MACKEY, Neale",""],
["mackey, patrick","382","Mackey, Patrick",""],
["mackey, thomas","380","MACKEY, Thomas",""],
["mackey, thomas","386","MACKEY, Thomas",""],
["mackey, william","324","MacKey, William",""],
["mackie, john","333","Mackie, John",""],
["mahaffee, thomas e","123","Mahaffee, Thomas E",""],
["mahaffey, alexander","928","Mahaffey, Alexander",""],
["mahaffey, amanda","122","Mahaffey, Amanda",""],
["mahaffey, andrew deaver","918","Mahaffey, Andrew Deaver",""],
["mahaffey, ann","917","Mahaffey, Ann",""],
["mahaffey, benjamin","925","Mahaffey, Benjamin",""],
["mahaffey, charles","935","Mahaffey, Charles",""],
["mahaffey, christopher columbus","88","Mahaffey, Christopher Columbus",""],
["mahaffey, clarissa ann","916","Mahaffey, Clarissa Ann",""],
["mahaffey, desdamond clemantine destie","49","Mahaffey, Desdamond Clemantine Destie",""],
["mahaffey, edward","927","Mahaffey, Edward",""],
["mahaffey, elizabeth","93","Mahaffey, Elizabeth",""],
["mahaffey, elizabeth","912","Mahaffey, Elizabeth",""],
["mahaffey, elizabeth","921","Mahaffey, Elizabeth",""],
["mahaffey, elizabeth","931","Mahaffey, Elizabeth",""],
["mahaffey, elizabeth","939","Mahaffey, Elizabeth",""],
["mahaffey, ester","97","Mahaffey, Ester",""],
["mahaffey, francis marion","87","Mahaffey, Francis Marion",""],
["mahaffey, hugh","924","Mahaffey, Hugh",""],
["mahaffey, hugh","926","Mahaffey, Hugh",""],
["mahaffey, jenetta jennet wells","934","Mahaffey, Jenetta Jennet Wells",""],
["mahaffey, jeremiah a","70","Mahaffey, Jeremiah A",""],
["mahaffey, jerry l","98","Mahaffey, Jerry L",""],
["mahaffey, john thomas","922","Mahaffey, John Thomas",""],
["mahaffey, joseph","919","Mahaffey, Joseph",""],
["mahaffey, joseph","932","Mahaffey, Joseph",""],
["mahaffey, joseph","937","Mahaffey, Joseph",""],
["mahaffey, joseph h","911","Mahaffey, Joseph H",""],
["mahaffey, joseph mchaffey","915","Mahaffey, Joseph McHaffey",""],
["mahaffey, lone","101","Mahaffey, Lone",""],
["mahaffey, margaret","92","Mahaffey, Margaret",""],
["mahaffey, mary","920","Mahaffey, Mary",""],
["mahaffey, mary ann  polly ","910","Mahaffey, Mary Ann  Polly ",""],
["mahaffey, maud","95","Mahaffey, Maud",""],
["mahaffey, rebecca jane","923","Mahaffey, Rebecca Jane",""],
["mahaffey, robinie kennedy hillen","936","Mahaffey, Robinie Kennedy Hillen",""],
["mahaffey, rosannah","933","Mahaffey, Rosannah",""],
["mahaffey, rose","938","Mahaffey, Rose",""],
["mahaffey, rowland","930","Mahaffey, Rowland",""],
["mahaffey, ruby","100","Mahaffey, Ruby",""],
["mahaffey, ruth","99","Mahaffey, Ruth",""],
["mahaffey, sarah j.","89","Mahaffey, Sarah J.",""],
["mahaffey, vertie","96","Mahaffey, Vertie",""],
["mahaffey, william","121","Mahaffey, William",""],
["mahaffey, william","909","Mahaffey, William",""],
["mahaffey, william n.","913","Mahaffey, William N.",""],
["mahaffy, mary","238","Mahaffy, Mary",""],
["marah greene/, maria","496","Marah Greene/, Maria",""],
["maxfield, margaret","1387","MAXFIELD, MARGARET",""],
["maxwell, mary","1178","Maxwell, Mary",""],
["may, john","791","May, John",""],
["may, john","879","May, John",""],
["may, mary","428","May, Mary",""],
["may, mary","785","May, Mary",""],
["may, mary","787","May, Mary",""],
["may, mary","788","May, Mary",""],
["may, sarah","880","May, Sarah",""],
["mcbee, susan","77","McBee, Susan",""],
["mcbee, susanna anna","132","Mcbee, Susanna Anna",""],
["mcconnell, prudence elizabeth","390","McConnell, Prudence Elizabeth",""],
["mccoy, archibald","318","Mccoy, Archibald",""],
["mccoy, hannah","316","Mccoy, Hannah",""],
["mccoy, mary","325","McCoy, Mary",""],
["mcdowell, jane","174","McDowell, Jane",""],
["mchaffey, rowland","929","Mchaffey, Rowland",""],
["mckee, alexander","379","McKee, Alexander",""],
["mckee, alexander","387","McKee, Alexander",""],
["mckee, david","330","Mckee, David",""],
["mckee, david b","315","Mckee, David B",""],
["mckee, ebenezer","301","Mckee, Ebenezer",""],
["mckee, ebenezer","305","Mckee, Ebenezer",""],
["mckee, ebenezer","327","MCKEE, Ebenezer",""],
["mckee, edward","326","Mckee, Edward",""],
["mckee, hannah","297","McKee, Hannah",""],
["mckee, joanna","303","McKee, Joanna",""],
["mckee, john","331","Mckee, John",""],
["mckee, john","334","MCKEE, John",""],
["mckee, judith","309","McKee, Judith",""],
["mckee, miribah","307","McKee, Miribah",""],
["mckee, robert","385","Mckee, Robert",""],
["mckee, steward","293","McKee, Steward",""],
["mckee, susanna","308","McKee, Susanna",""],
["mckee, wilson","306","Mckee, Wilson",""],
["mckie, james","312","Mckie, James",""],
["mckie, james","374","Mckie, James",""],
["mckie, james","376","Mckie, James",""],
["mc neal, agnes l","114","Mc Neal, Agnes L",""],
["mcneal, albert warren","113","McNeal, Albert Warren",""],
["mc neal, cecil w","117","Mc Neal, Cecil W",""],
["mc neal, cliford l","115","Mc Neal, Cliford L",""],
["mc neal, edna i","116","Mc Neal, Edna I",""],
["mc neal, lyle w","119","Mc Neal, Lyle W",""],
["mcneal, nora frances","108","McNeal, Nora Frances",""],
["mcneal, nora frances","222","McNeal, Nora Frances",""],
["mc neal, prudence e","112","Mc Neal, Prudence E",""],
["mc neal, thera f","118","Mc Neal, Thera F",""],
["medina acuna, emirelies","870","Medina Acuna, Emirelies",""],
["merrihew, zilpha","746","Merrihew, Zilpha",""],
["miller, charity","1062","Miller, Charity",""],
["miller, ella amantha","1760","Miller, Ella Amantha",""],
["mills, john","906","Mills, John",""],
["mills, mary","808","Mills, Mary",""],
["mitchell, john","999","Mitchell, John",""],
["mitchell, mary","962","Mitchell, Mary",""],
["moon, maria","1685","Moon, Maria",""],
["mortain, mauger count of","1809","MORTAIN, Mauger Count Of",""],
["moyce, elisabeth","335","Moyce, Elisabeth",""],
["neederman, catherine","184","Neederman, Catherine",""],
["neves, agnas","844","Neves, Agnas",""],
["neves, agnes ann","838","Neves, Agnes Ann",""],
["neves, lady agnes","577","Neves, Lady Agnes",""],
["neves, william","843","Neves, William",""],
["normandy, béatrix of of","1812","Normandy, Béatrix of of",""],
["normandy, emma of","1811","Normandy, Emma of",""],
["normandy, fressenda of of","1819","Normandy, Fressenda of of",""],
["normandy, havoise hedwige of","1818","Normandy, Havoise Hedwige of",""],
["normandy, mahaud of","1807","Normandy, Mahaud of",""],
["normandy, morella muriella of","1806","Normandy, Morella Muriella of",""],
["normandy, richard i","1801","Normandy, Richard I",""],
["normandy, robert of","1810","Normandy, Robert of",""],
["normandy, william guillaume i long sword longue espée 2nd of","1804","Normandy, William Guillaume I Long Sword longue Espée 2nd of",""],
["northwode, geoffrey","664","Northwode, Geoffrey",""],
["norton, nancy","1541","Norton, Nancy",""],
["nulton, sarah nancy","1451","Nulton, Sarah Nancy",""],
["oddyle, elizibeth","1595","Oddyle, Elizibeth",""],
["osborn, demaris","1368","osborn, Demaris",""],
["paine, anthony","821","Paine, ANTHONY",""],
["paine, dorothy","829","Paine, Dorothy",""],
["paine, elizabeth","832","Paine, Elizabeth",""],
["paine, jane","836","Paine, Jane",""],
["paine, john","1482","Paine, John",""],
["paine, lady elizabeth","528","Paine, Lady Elizabeth",""],
["paine, ralph","1483","Paine, Ralph",""],
["paine, susan","825","Paine, Susan",""],
["paine, susan","839","Paine, Susan",""],
["paine, william","1487","Paine, William",""],
["palmer, ruth evalina","44","Palmer, Ruth Evalina",""],
["partridge, elizabeth","762","Partridge, Elizabeth",""],
["patterson, margaret","332","Patterson, Margaret",""],
["payne, anne","840","Payne, Anne",""],
["payne, anne","1481","Payne, Anne",""],
["payne, dorothy","841","PAYNE, Dorothy",""],
["payne, frances","828","Payne, Frances",""],
["payne, judith","823","Payne, Judith",""],
["payne, phoebe","824","Payne, Phoebe",""],
["payne, phoebe","834","Payne, Phoebe",""],
["payne, richard","833","Payne, Richard",""],
["payne, richard","835","Payne, Richard",""],
["payne, richard","842","Payne, Richard",""],
["payne, robert","830","PAYNE, Robert",""],
["payne, susan","837","Payne, Susan",""],
["payne, thomas","827","PAYNE, Thomas",""],
["payne, thomas","1485","Payne, Thomas",""],
["payne, thomas","1488","Payne, Thomas",""],
["payne, william","578","Payne, William",""],
["payne, william","826","Payne, William",""],
["payne, william","845","Payne, William",""],
["payne, william","1484","Payne, William",""],
["payne, william","1489","Payne, William",""],
["peck, ann","758","Peck, Ann",""],
["phillips, anne","1615","Phillips, Anne",""],
["potter, mary","1613","Potter, Mary",""],
["pratt, benajah","1426","Pratt, Benajah",""],
["pratt, hannah","708","Pratt, Hannah",""],
["pratt, jonathan","1425","Pratt, Jonathan",""],
["pratt, joshua","773","Pratt, Joshua",""],
["pratt, mary","1424","Pratt, Mary",""],
["price, elizabeth","1176","Price, Elizabeth",""],
["prouty, elias","1678","Prouty, Elias",""],
["prouty, ezra","1675","Prouty, Ezra",""],
["prouty, ira","1684","Prouty, Ira",""],
["prouty, john","1683","Prouty, John",""],
["prouty, joseph ward","1680","Prouty, Joseph Ward",""],
["prouty, lester","1676","Prouty, Lester",""],
["prouty, lewis e-","1682","Prouty, Lewis E-",""],
["prouty, lucy","1677","Prouty, Lucy",""],
["prouty, matilda","1679","Prouty, Matilda",""],
["prouty, nancy","1681","Prouty, Nancy",""],
["pulford hammond/, robert","1786","Pulford Hammond/, Robert",""],
["quithel, susannah","1617","Quithel, Susannah",""],
["ragland, catherine  katie ","1570","Ragland, Catherine  Katie ",""],
["randall, mary","506","Randall, Mary",""],
["randel, mercy","508","Randel, Mercy",""],
["reed, hannah","191","Reed, Hannah",""],
["rice, emiline","1378","Rice, Emiline",""],
["rice, emiline","1604","Rice, Emiline",""],
["riley, elizabeth","998","Riley, Elizabeth",""],
["robinson, adeline eliza","1702","Robinson, Adeline Eliza",""],
["robinson, mary e.","1721","Robinson, Mary E.",""],
["robles jimenez, milena","869","Robles Jimenez, Milena",""],
["robles parada, rogelio antonio","868","Robles Parada, Rogelio Antonio",""],
["robles vanegas, manuel maria","866","Robles Vanegas, Manuel Maria",""],
["rognvaldsson, rollo","1823","Rognvaldsson, Rollo",""],
["rouen, robert archbishop of","1808","Rouen, Robert Archbishop Of",""],
["rowell, louise","35","Rowell, Louise",""],
["rowell, lucy","40","Rowell, Lucy",""],
["rowlingson, celestia estelle","47","Rowlingson, Celestia Estelle",""],
["rush, almira","197","Rush, Almira",""],
["rush, benjamin","1453","Rush, Benjamin",""],
["rush, calvin","1443","Rush, Calvin",""],
["rush, george","1446","Rush, George",""],
["rush, hiram","1450","Rush, Hiram",""],
["rush, john","1445","Rush, John",""],
["rush, john","1448","Rush, John",""],
["rush, minerva","1449","Rush, Minerva",""],
["rush, ozro","1447","Rush, Ozro",""],
["rush, peter","208","Rush, Peter",""],
["samson, priscilla","511","Samson, Priscilla",""],
["sargent, arthur c.","885","Sargent, Arthur C.",""],
["sargent, austin d.","887","Sargent, Austin D.",""],
["sargent, catharine h drake","361","Sargent, Catharine H Drake",""],
["sargent, emma","888","Sargent, Emma",""],
["sargent, lucy","884","Sargent, Lucy",""],
["sargent, timothy","886","Sargent, Timothy",""],
["scissum, roxanne delilah","695","Scissum, Roxanne Delilah",""],
["seargent, emiline","889","Seargent, Emiline",""],
["seargent, myron","362","Seargent, Myron",""],
["shaw, marion mary","1523","Shaw, Marion Mary",""],
["shekley, mary","394","Shekley, Mary",""],
["shelton, elizabeth","1572","Shelton, Elizabeth",""],
["sheperd, elizabeth","455","Sheperd, Elizabeth",""],
["shepherd, hannah","460","Shepherd, Hannah",""],
["sherman, dorothy","1251","Sherman, Dorothy",""],
["shotorban, tina a","54","Shotorban, Tina A",""],
["sinclair, ann","1522","Sinclair, Ann",""],
["singleton, mary","1080","Singleton, Mary",""],
["singleton, robert","1098","Singleton, Robert",""],
["slater, mahala ann","199","Slater, Mahala Ann",""],
["smith, margaret m","237","Smith, Margaret M",""],
["smith, nancy octavia","677","Smith, Nancy Octavia",""],
["smith, unknown","1050","Smith, Unknown",""],
["snider, elizabeth","120","Snider, Elizabeth",""],
["spann, catherine fox","1697","Spann, Catherine Fox",""],
["spaulding, amy","256","Spaulding, Amy",""],
["spears, delilah dilly","860","Spears, Delilah Dilly",""],
["spears, friend","863","Spears, Friend",""],
["spears, friend w","697","Spears, Friend W",""],
["spears, hazeltine","686","Spears, Hazeltine",""],
["spears, hazeltine","690","Spears, Hazeltine",""],
["spears, hezekiah","864","Spears, Hezekiah",""],
["spears, james","684","Spears, James",""],
["spears, james","856","Spears, James",""],
["spears, john","859","Spears, John",""],
["spears, joshua","861","Spears, Joshua",""],
["spears, joshua","862","Spears, Joshua",""],
["spears, joshua f","701","Spears, Joshua F",""],
["spears, josiah","699","Spears, Josiah",""],
["spears, libbie","688","Spears, Libbie",""],
["spears, libbie","692","Spears, Libbie",""],
["spears, martha","687","Spears, Martha",""],
["spears, martha ann","858","Spears, Martha Ann",""],
["spears, martha jane","691","Spears, Martha Jane",""],
["spears, mary s","702","Spears, Mary S",""],
["spears, nannie","689","Spears, Nannie",""],
["spears, nannie p.","668","Spears, Nannie P.",""],
["spears, roxana","693","Spears, Roxana",""],
["spears, sarah","698","SPEARS, SARAH",""],
["spears, sibbie","700","Spears, Sibbie",""],
["spears, william","676","Spears, William",""],
["spears, william","694","Spears, William",""],
["spears, william","696","Spears, William",""],
["spears, william","857","Spears, William",""],
["spencer, lois","1732","Spencer, Lois",""],
["spooner, abagail","716","Spooner, Abagail",""],
["spooner, alice","714","Spooner, Alice",""],
["spooner, alice","721","Spooner, Alice",""],
["spooner, alice warner","718","Spooner, Alice Warner",""],
["spooner, benjamin","707","Spooner, Benjamin",""],
["spooner, benjamin","710","Spooner, Benjamin",""],
["spooner, ebenezer","720","Spooner, Ebenezer",""],
["spooner, ebenezer","753","Spooner, Ebenezer",""],
["spooner, elizabeth","729","Spooner, Elizabeth",""],
["spooner, hannah","756","Spooner, Hannah",""],
["spooner, hannah","771","Spooner, Hannah",""],
["spooner, hannah pratt","760","Spooner, Hannah Pratt",""],
["spooner, isaac","724","Spooner, Isaac",""],
["spooner, isaac","757","Spooner, Isaac",""],
["spooner, jabesh","717","Spooner, Jabesh",""],
["spooner, jemima","728","Spooner, Jemima",""],
["spooner, john","759","Spooner, John",""],
["spooner, john","763","Spooner, John",""],
["spooner, john","1422","Spooner, John",""],
["spooner, joseph","706","Spooner, Joseph",""],
["spooner, joseph","712","Spooner, Joseph",""],
["spooner, joshua","705","Spooner, Joshua",""],
["spooner, joshua","711","Spooner, Joshua",""],
["spooner, martha","752","Spooner, Martha",""],
["spooner, martha","768","Spooner, Martha",""],
["spooner, mary","713","Spooner, Mary",""],
["spooner, mary","723","Spooner, Mary",""],
["spooner, mary","755","Spooner, Mary",""],
["spooner, mercy","751","Spooner, Mercy",""],
["spooner, mercy","764","Spooner, Mercy",""],
["spooner, micah","727","Spooner, Micah",""],
["spooner, nathaniel","715","Spooner, Nathaniel",""],
["spooner, nathaniel","726","Spooner, Nathaniel",""],
["spooner, rebecca","1423","Spooner, Rebecca",""],
["spooner, rebeckah","725","Spooner, Rebeckah",""],
["spooner, samuel","761","Spooner, Samuel",""],
["spooner, samuel","766","Spooner, Samuel",""],
["spooner, samuel","770","Spooner, Samuel",""],
["spooner, sarah","430","Spooner, Sarah",""],
["spooner, sarah","722","Spooner, Sarah",""],
["spooner, sarah","754","Spooner, Sarah",""],
["spooner, sarah","767","Spooner, Sarah",""],
["spooner, sarah","769","Spooner, Sarah",""],
["spooner, thomas","1421","Spooner, Thomas",""],
["spooner, william","453","Spooner, William",""],
["spooner, william","454","Spooner, William",""],
["spooner, william","709","Spooner, William",""],
["spooner, william","765","SPOONER, William",""],
["steward, robert","598","Steward, Robert",""],
["strangeman, polly","1217","Strangeman, Polly",""],
["strate, sarah","1444","Strate, Sarah",""],
["swift, hannah","1456","Swift, Hannah",""],
["swift, jireh","733","Swift, Jireh",""],
["taber, mary","475","Taber, Mary",""],
["taylor ?, mary","1151","Taylor ?, MARY",""],
["terry, deborah","1662","Terry, Deborah",""],
["thayer, laura","1294","Thayer, Laura",""],
["thompson, mary","239","Thompson, Mary",""],
["thompson, matilda","102","Thompson, Matilda",""],
["thorne, phoebe","1299","Thorne, Phoebe",""],
["tinsley, emily a","349","Tinsley, EMILY A",""],
["torrey, sarah","881","Torrey, Sarah",""],
["tripp, george","1494","Tripp, George",""],
["tripp, nathaniel","776","Tripp, Nathaniel",""],
["tripp, reginald","1493","Tripp, Reginald",""],
["trippe, johannes","775","Trippe, Johannes",""],
["trippe, rose","573","Trippe, Rose",""],
["trippe, rose","608","Trippe, Rose",""],
["trippe, william","596","Trippe, William",""],
["trippe, william","622","Trippe, William",""],
["trippe, william","777","Trippe, William",""],
["trippe, william trippe","613","Trippe, William Trippe",""],
["tuidill, mary a","1648","Tuidill, Mary A",""],
["turner, mary","890","Turner, Mary",""],
["unk, unk","368","unk, unk",""],
["unknown, margaret","1048","unknown, Margaret",""],
["unknown, mary","228","Unknown, Mary",""],
["valler, ann","780","Valler, Ann",""],
["valler, anne","784","Valler, Anne",""],
["valler, john","429","Valler, John",""],
["valler, john","781","Valler, John",""],
["valler, lois","400","Valler, Lois",""],
["valler, sarah","778","Valler, Sarah",""],
["valler, silas","783","Valler, Silas",""],
["valler, silvanus","782","Valler, Silvanus",""],
["valler, simeon","779","Valler, Simeon",""],
["valler, simeon","786","Valler, Simeon",""],
["valler, simeon","789","Valler, Simeon",""],
["vanegas tarriba, pabla","867","Vanegas Tarriba, Pabla",""],
["van spriell","34","Van Spriell",""],
["vincent, elizabeth","848","Vincent, Elizabeth",""],
["vincent, elizabeth","851","Vincent, Elizabeth",""],
["vincent, henry","850","Vincent, Henry",""],
["vincent, john","532","Vincent, John",""],
["vincent, john","847","Vincent, John",""],
["vincent, john","854","Vincent, John",""],
["vincent, mary","480","Vincent, Mary",""],
["vincent vinson, sarah","849","Vincent Vinson, Sarah",""],
["walker, sarah","730","Walker, Sarah",""],
["walker, william","1418","Walker, William",""],
["warren, abigail","1406","Warren, Abigail",""],
["warren, abigail","1429","Warren, Abigail",""],
["warren, alice","452","Warren, Alice",""],
["warren, alice","1407","Warren, Alice",""],
["warren, ann","1431","Warren, Ann",""],
["warren, anna","1430","Warren, Anna",""],
["warren, anne","790","Warren, Anne",""],
["warren, benjamin","1241","Warren, Benjamin",""],
["warren, elizabeth","1428","Warren, Elizabeth",""],
["warren, hannah","1401","Warren, Hannah",""],
["warren, hope","1242","Warren, Hope",""],
["warren, hope","1395","Warren, Hope",""],
["warren, hope","1411","WARREN, Hope",""],
["warren, jabez","1399","warren, jabez",""],
["warren, jabez","1413","WARREN, Jabez",""],
["warren, jabez","1416","Warren, Jabez",""],
["warren, james","1246","Warren, James",""],
["warren, james","1400","Warren, James",""],
["warren, jane","1404","WARREN, Jane",""],
["warren, joanna sarah","1244","Warren, Joanna Sarah",""],
["warren, john","1245","Warren, John",""],
["warren, john","1397","Warren, John",""],
["warren, john","1409","Warren, John",""],
["warren, joseph","1427","Warren, Joseph",""],
["warren, martha c","86","Warren, Martha C",""],
["warren, mary","1396","Warren, Mary",""],
["warren, mary","1410","WARREN, Mary",""],
["warren, mary","1415","Warren, Mary",""],
["warren, mary","1432","Warren, Mary",""],
["warren, mercy","1403","Warren, Mercy",""],
["warren, nathaniel","731","Warren, Nathaniel",""],
["warren, nathaniel","1402","Warren, Nathaniel",""],
["warren, richard","882","Warren, Richard",""],
["warren, richard","1394","Warren, Richard",""],
["warren, richard","1398","Warren, Richard",""],
["warren, samuel","1243","Warren, Samuel",""],
["warren, sarah","805","Warren, Sarah",""],
["warren, sarah","1408","Warren, Sarah",""],
["warren, sarah","1414","Warren, Sarah",""],
["warren, son","1405","Warren, SON",""],
["watts, elizabeth","943","Watts, Elizabeth",""],
["watts, elizabeth","964","Watts, Elizabeth",""],
["watts, sarah","1576","Watts, Sarah",""],
["whipple, mary","1611","Whipple, Mary",""],
["whiteside, dorothy","210","Whiteside, Dorothy",""],
["whiteside, dorothy","213","Whiteside, Dorothy",""],
["whitney, abigail","1202","Whitney, Abigail",""],
["whitten, emma augusta","366","Whitten, Emma Augusta",""],
["whitten, ethel m","364","Whitten, Ethel M",""],
["whitten, julia ann sargeant","30","Whitten, Julia Ann Sargeant",""],
["whitten, martha etta","367","Whitten, Martha Etta",""],
["whitten, rosa","365","Whitten, Rosa",""],
["whitten, walter watson","363","Whitten, Walter Watson",""],
["wife","987","Wife",""],
["williams, anna","1337","Williams, Anna",""],
["wilson, sarah","302","Wilson, Sarah",""],
["wilson, sarah","375","Wilson, Sarah",""],
["winchester, mary elizabeth","240","Winchester, Mary Elizabeth",""],
["wing, daniel","1457","Wing, Daniel",""],
["wing, john, jr.","440","Wing, John, Jr.",""],
["wing, lydia","820","Wing, Lydia",""],
["wyman, mary","1190","WYMAN, Mary",""],
["young, eunice","1252","Young, Eunice",""]];